using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using RingSport.Core;

namespace RingSport.Level
{
    /// <summary>
    /// Body parts the dog's pounce can grab on the decoy ragdoll. Every value
    /// maps to a bone with its own rigidbody on the Malbers Steve ragdoll
    /// (validated by DecoySetup at build time), so any of them can be the
    /// kinematic mouth pin: flee attack takes the right forearm, the face
    /// attack will take the head, etc.
    /// </summary>
    public enum DecoyLimb
    {
        RightForearm,
        LeftForearm,
        RightHand,
        LeftHand,
        RightUpperArm,
        LeftUpperArm,
        Head,
        Chest,
        RightThigh,
        LeftThigh,
        RightCalf,
        LeftCalf,
        RightFoot,
        LeftFoot,
    }

    /// <summary>
    /// The human decoy actor: the Malbers placeholder human (Steve) with a
    /// runner-specific Animator (run / strafe-lean / fall-forward) and the
    /// catch handover for the flee attack - the animated model swaps to the
    /// Malbers Steve ragdoll, the RIGHT FOREARM is pinned kinematically to the
    /// dog's mouth (a sleeve-style grab), and every other joint keeps its
    /// animated pose and velocity so the body continues its fall and
    /// dangles/bounces off the ground. Also intended to host the decoy for the
    /// face attack and decoy battle mini levels. Prefab + Animator are
    /// generated by Tools > RingSport > Setup Decoy.
    /// </summary>
    public class DecoyController : MonoBehaviour
    {
        [SerializeField] private Animator animator;
        [Tooltip("Malbers 'Steve Ragdoll' prefab; the animated model swaps to it when caught.")]
        [SerializeField] private GameObject ragdollPrefab;

        [Header("Blend Damping")]
        [SerializeField] private float moveSpeedDampTime = 0.2f;
        [SerializeField] private float strafeDampTime = 0.12f;

        [Header("Catch Ragdoll")]
        [Tooltip("Limb the dog's mouth grabs when AttachToMouth is called without an explicit target (flee attack = sleeve-style right forearm).")]
        [SerializeField] private DecoyLimb defaultGrabLimb = DecoyLimb.RightForearm;
        [Tooltip("TESTING: each catch without an explicit target grabs a random arm/leg limb instead of the default, so every grab point gets exercised. Head/torso are excluded - they still ragdoll.")]
        [SerializeField] private bool randomizeGrabLimb = true;
        [Tooltip("How far in front of the mouth bone the grabbed bone is pinned (along the dog model's forward).")]
        [SerializeField] private float grabForwardOffset = 0.2f;
        [SerializeField] private float grabUpOffset = 0.02f;
        [Tooltip("Seconds over which the grabbed limb settles from where the bite lands into the mouth offset. The dog steers onto the limb during the pounce, so this only covers the last few centimeters.")]
        [SerializeField] private float grabBlendSeconds = 0.1f;
        [Tooltip("Cap on the per-bone velocity carried over from the animation into the ragdoll (m/s).")]
        [SerializeField] private float boneVelocityClamp = 8f;
        [Tooltip("Bounciness of the ragdoll limbs against the ground.")]
        [SerializeField] [Range(0f, 1f)] private float groundBounciness = 0.35f;
        [SerializeField] private float randomTumble = 1.5f;

        private static readonly int MoveSpeedHash = Animator.StringToHash("MoveSpeed");
        private static readonly int StrafeHash = Animator.StringToHash("Strafe");
        private static readonly int AnimSpeedHash = Animator.StringToHash("AnimSpeed");
        private static readonly int FallHash = Animator.StringToHash("Fall");
        private static readonly int PowerUpHash = Animator.StringToHash("PowerUp");
        private static readonly int LocomotionStateHash = Animator.StringToHash("Locomotion");

        // Whether the generated controller has the PowerUp trigger (guards
        // against a stale pre-v11 controller so SetTrigger never warns)
        private bool? hasPowerUpParam;

        // Previous-frame bone snapshot of the animated model, for the
        // animation -> physics velocity handover at the catch
        private Transform[] trackedBones = System.Array.Empty<Transform>();
        private Vector3[] bonePositions = System.Array.Empty<Vector3>();
        private Vector3[] prevBonePositions = System.Array.Empty<Vector3>();
        private float captureDeltaTime;
        private int captureCount;

        // Velocities need positions from two frames
        private bool HasVelocityCapture => captureCount >= 2;

        private GameObject ragdollInstance;
        private Transform mouthAnchor;
        private PhysicsMaterial bounceMaterial;
        private float modelScale = 1f;
        private bool limbChosen;
        private Transform pendingGrabBone;

        public bool IsCarried { get; private set; }

        /// <summary>
        /// The limb the catch will grab, decided when the pounce fires (so the
        /// dog can steer its leap onto it before the bite).
        /// </summary>
        public DecoyLimb PendingGrabLimb { get; private set; }

        /// <summary>Exposed so the scene warm-up can pre-deserialize it.</summary>
        public GameObject RagdollPrefab => ragdollPrefab;

        private void Awake()
        {
            if (animator == null)
                animator = GetComponentInChildren<Animator>(true);

            if (animator != null)
            {
                // Same constraints as the dog: unscaled time so freezes can't
                // stall one-shots, no root motion so code owns all travel.
                animator.updateMode = AnimatorUpdateMode.UnscaledTime;
                animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
                animator.applyRootMotion = false;

                trackedBones = animator.GetComponentsInChildren<Transform>(true);
                bonePositions = new Vector3[trackedBones.Length];
                prevBonePositions = new Vector3[trackedBones.Length];

                // The model is scaled up in the prefab; stride length scales
                // with it, so locomotion cycles slow down by the same factor to
                // keep the feet in sync with the same world scroll speed
                modelScale = Mathf.Max(0.01f, animator.transform.lossyScale.z);
            }
        }

        /// <summary>
        /// moveSpeed: 0 = idle, 1 = jog, 2 = sprint. strafe: -1..1 lane-change
        /// lean. animSpeed: playback multiplier on the locomotion cycle.
        /// </summary>
        public void UpdateLocomotion(float moveSpeed, float strafe, float animSpeed, float deltaTime)
        {
            if (animator == null || IsCarried)
                return;

            animator.SetFloat(MoveSpeedHash, moveSpeed, moveSpeedDampTime, deltaTime);
            animator.SetFloat(StrafeHash, Mathf.Clamp(strafe, -1f, 1f), strafeDampTime, deltaTime);
            animator.SetFloat(AnimSpeedHash, animSpeed / modelScale);
        }

        /// <summary>
        /// Fall-forward one-shot, fired when the dog pounces. Also locks in the
        /// grab limb so the pounce can steer toward it - the catch then grabs
        /// the same limb.
        /// </summary>
        public void TriggerFall()
        {
            TriggerFall(randomizeGrabLimb
                ? RandomLimbPool[Random.Range(0, RandomLimbPool.Length)]
                : defaultGrabLimb);
        }

        /// <summary>
        /// Fall-forward one-shot with an explicit grab target - the face attack
        /// passes the limb the player picked in its quick time event.
        /// </summary>
        public void TriggerFall(DecoyLimb limb)
        {
            if (animator == null || IsCarried)
                return;

            PendingGrabLimb = limb;
            limbChosen = true;
            pendingGrabBone = FindTrackedBone(PrimaryBoneName(limb));
            GameLog.Info($"[DecoyController] Pounce target: {PendingGrabLimb}");

            // The fall clip carries its drop/stumble in root motion; let it own
            // the model's local travel for the topple (locomotion keeps root
            // motion off so code owns all travel while running)
            animator.applyRootMotion = true;
            animator.SetTrigger(FallHash);
        }

        /// <summary>
        /// Arms-up power-up taunt: the face attack fires this as the decoy
        /// squares up, so the frozen QTE holds an aggressive pose with the
        /// limb targets spread wide. No-ops gracefully on a stale controller.
        /// </summary>
        public void TriggerPowerUp()
        {
            if (animator == null || IsCarried || !HasPowerUpParam)
                return;
            animator.SetTrigger(PowerUpHash);
        }

        /// <summary>
        /// Blends a one-shot pose (the power-up taunt) back into the
        /// locomotion blend - the dodge escape bolts mid-pose.
        /// </summary>
        public void ResumeLocomotion()
        {
            if (animator == null || IsCarried)
                return;
            if (HasPowerUpParam)
                animator.ResetTrigger(PowerUpHash);
            animator.CrossFadeInFixedTime(LocomotionStateHash, 0.2f, 0);
        }

        private bool HasPowerUpParam
        {
            get
            {
                if (!hasPowerUpParam.HasValue)
                {
                    hasPowerUpParam = false;
                    if (animator != null)
                    {
                        foreach (var parameter in animator.parameters)
                        {
                            if (parameter.nameHash == PowerUpHash)
                            {
                                hasPowerUpParam = true;
                                break;
                            }
                        }
                    }
                }
                return hasPowerUpParam.Value;
            }
        }

        /// <summary>
        /// World position of a limb's bone on the ANIMATED model - the anchor
        /// the face attack's screen-space tap targets track each frame.
        /// </summary>
        public Vector3 GetLimbPosition(DecoyLimb limb)
        {
            Transform bone = FindTrackedBone(PrimaryBoneName(limb));
            if (bone != null)
                return bone.position;
            Transform model = animator != null ? animator.transform : transform;
            return model.position + Vector3.up * 0.8f * modelScale;
        }

        /// <summary>
        /// World position of the pending grab limb's bone on the ANIMATED model
        /// (valid during the fall, before the ragdoll swap) - the point the
        /// dog's pounce steers its mouth onto.
        /// </summary>
        public Vector3 GetGrabLimbPosition()
        {
            if (pendingGrabBone != null)
                return pendingGrabBone.position;
            Transform model = animator != null ? animator.transform : transform;
            return model.position + Vector3.up * 0.8f * modelScale;
        }

        private Transform FindTrackedBone(string normalizedName)
        {
            foreach (var bone in trackedBones)
            {
                if (bone != null && NormalizeBoneName(bone.name) == normalizedName)
                    return bone;
            }
            return null;
        }

        private void LateUpdate()
        {
            if (IsCarried || animator == null)
                return;

            // Snapshot bone positions after animation so the catch can compute
            // per-bone velocities from the last two frames
            float dt = Time.deltaTime;
            if (dt <= 0f)
                return;

            var swap = prevBonePositions;
            prevBonePositions = bonePositions;
            bonePositions = swap;
            for (int i = 0; i < trackedBones.Length; i++)
                bonePositions[i] = trackedBones[i] != null ? trackedBones[i].position : Vector3.zero;

            captureDeltaTime = dt;
            captureCount++;
        }

        // Arms and legs only - the head and chest grabs exist for the future
        // face attack etc., which pass their limb explicitly
        private static readonly DecoyLimb[] RandomLimbPool =
        {
            DecoyLimb.RightForearm, DecoyLimb.LeftForearm,
            DecoyLimb.RightHand, DecoyLimb.LeftHand,
            DecoyLimb.RightUpperArm, DecoyLimb.LeftUpperArm,
            DecoyLimb.RightThigh, DecoyLimb.LeftThigh,
            DecoyLimb.RightCalf, DecoyLimb.LeftCalf,
            DecoyLimb.RightFoot, DecoyLimb.LeftFoot,
        };

        /// <summary>
        /// Catch using the limb the pounce aimed at (locked in by TriggerFall),
        /// falling back to the default/randomized choice for callers that
        /// never pounced.
        /// </summary>
        public void AttachToMouth(Transform mouth, Vector3 carryForward, Transform playerRoot)
        {
            DecoyLimb limb = limbChosen
                ? PendingGrabLimb
                : randomizeGrabLimb
                    ? RandomLimbPool[Random.Range(0, RandomLimbPool.Length)]
                    : defaultGrabLimb;
            AttachToMouth(mouth, carryForward, playerRoot, limb);
        }

        /// <summary>
        /// The catch: swaps the animated model for the ragdoll mid-pose, snaps
        /// the targeted limb to the mouth bone (kinematic, parented under it -
        /// no force path back into the dog), and lets every other joint
        /// continue the fall with its animated velocity so the body dangles
        /// and bounces off the ground during the carry. Any DecoyLimb can be
        /// the pin - future mini levels (face attack, decoy battle) pass their
        /// own target.
        /// </summary>
        public void AttachToMouth(Transform mouth, Vector3 carryForward, Transform playerRoot, DecoyLimb limb)
        {
            if (IsCarried || mouth == null)
                return;

            IsCarried = true;

            Transform model = animator != null ? animator.transform : transform;
            Vector3 grabTarget = mouth.position + carryForward.normalized * grabForwardOffset + Vector3.up * grabUpOffset;

            if (ragdollPrefab == null)
            {
                // No ragdoll available - carry the whole animated model like the
                // old sphere did, frozen in its fall pose
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }

            // Spawn under an INACTIVE holder: joints capture their physics
            // frames the moment an active instance awakes, so the scale, pose
            // and kinematic flags must all be final BEFORE activation. Scaling
            // an already-awake ragdoll leaves every joint solving against
            // stale scale-1 anchors (the "detached ragdoll" bug).
            var spawnHolder = new GameObject("DecoyRagdollSpawn");
            spawnHolder.SetActive(false);
            ragdollInstance = Instantiate(ragdollPrefab, model.position, model.rotation, spawnHolder.transform);
            ragdollInstance.name = "DecoyRagdoll";
            ragdollInstance.transform.localScale = model.lossyScale;

            // Strip the Malbers behaviours; joints, rigidbodies and colliders stay
            foreach (var behaviour in ragdollInstance.GetComponentsInChildren<MonoBehaviour>(true))
                Destroy(behaviour);
            foreach (var anim in ragdollInstance.GetComponentsInChildren<Animator>(true))
                anim.enabled = false;

            // Gather the physics pieces NOW - the grabbed limb's subtree is
            // reparented out of this hierarchy below, and a later
            // GetComponentsInChildren would silently skip it (which previously
            // left the pin dynamic: nothing actually held the body)
            var bodies = ragdollInstance.GetComponentsInChildren<Rigidbody>(true);
            var colliders = ragdollInstance.GetComponentsInChildren<Collider>(true);
            var joints = ragdollInstance.GetComponentsInChildren<CharacterJoint>(true);

            CopyPose(model, ragdollInstance.transform);

            var grabBody = ResolveLimbBody(ragdollInstance.transform, limb);
            if (grabBody == null)
            {
                // Should never happen with the Malbers ragdoll (every DecoyLimb
                // maps to a rigidbody) - fall back to the whole-model carry
                GameLog.Warn($"[DecoyController] No rigidbody found for limb {limb} in the ragdoll - carrying the animated model instead.");
                Destroy(spawnHolder);
                ragdollInstance = null;
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }
            GameLog.Info($"[DecoyController] Pounce grab: {limb} -> {grabBody.name}");

            ConfigureBodies(bodies, colliders, joints, grabBody);

            // Anchor under the mouth bone; the kinematic grabbed bone is
            // parented to it so it rigidly follows the head animation.
            // Kinematic = infinite mass, so nothing the body does can push the
            // dog around. The anchor starts at the limb's CURRENT position -
            // the body stays exactly where the bite visually lands - and is
            // then yanked into the mouth over grabBlendSeconds (an instant
            // snap teleports the whole body by up to a limb's length).
            mouthAnchor = new GameObject("DecoyMouthAnchor").transform;
            mouthAnchor.position = grabBody.transform.position;
            mouthAnchor.rotation = grabBody.transform.rotation;
            mouthAnchor.SetParent(mouth, true);

            // Reparenting out of the inactive holder ACTIVATES the ragdoll -
            // physics wakes here, with final scale, pose and kinematic flags
            ragdollInstance.transform.SetParent(mouthAnchor, true);
            grabBody.transform.SetParent(mouthAnchor, true);
            Destroy(spawnHolder);

            ReleaseBodies(bodies, colliders, grabBody, playerRoot);

            StartCoroutine(BlendGrabToMouth(mouth.InverseTransformPoint(grabTarget)));

            // The animated model's job is done
            model.gameObject.SetActive(false);
        }

        /// <summary>
        /// Pulls the mouth anchor (and the kinematic limb pinned to it) from
        /// where the bite landed into the mouth, in jaw-local space so it
        /// keeps riding the head animation while it blends. The joints drag
        /// the rest of the body along, so the whole snatch reads as motion.
        /// </summary>
        private IEnumerator BlendGrabToMouth(Vector3 targetLocalPosition)
        {
            Vector3 startLocalPosition = mouthAnchor.localPosition;
            float elapsed = 0f;
            while (elapsed < grabBlendSeconds && mouthAnchor != null)
            {
                elapsed += Time.deltaTime;
                float k = Mathf.Clamp01(elapsed / grabBlendSeconds);
                k = k * k * (3f - 2f * k);
                mouthAnchor.localPosition = Vector3.Lerp(startLocalPosition, targetLocalPosition, k);
                yield return null;
            }
            if (mouthAnchor != null)
                mouthAnchor.localPosition = targetLocalPosition;
        }

        /// <summary>Pre-activation physics setup - flags apply when the bodies wake.</summary>
        private void ConfigureBodies(Rigidbody[] bodies, Collider[] colliders, CharacterJoint[] joints, Rigidbody grabBody)
        {
            if (bounceMaterial == null)
            {
                bounceMaterial = new PhysicsMaterial("DecoyBounce")
                {
                    bounciness = groundBounciness,
                    bounceCombine = PhysicsMaterialCombine.Maximum,
                    dynamicFriction = 0.5f,
                    staticFriction = 0.5f
                };
            }

            foreach (var ragdollCollider in colliders)
                ragdollCollider.sharedMaterial = bounceMaterial;

            // Joint projection snaps drifting limbs back to their sockets - the
            // main anti-twitch (same treatment as PlayerRagdoll)
            foreach (var joint in joints)
            {
                joint.enableProjection = true;
                joint.projectionDistance = 0.05f;
                joint.projectionAngle = 30f;
            }

            foreach (var body in bodies)
            {
                if (body == grabBody)
                {
                    // Kinematic bodies don't support continuous collision
                    body.collisionDetectionMode = CollisionDetectionMode.Discrete;
                    body.isKinematic = true;
                    continue;
                }

                body.isKinematic = false;
                body.useGravity = true;
                body.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
                body.interpolation = RigidbodyInterpolation.Interpolate;
                body.solverIterations = 8;
                body.sleepThreshold = 0.05f;
            }
        }

        /// <summary>
        /// Post-activation physics setup - collision ignores and velocities
        /// need live physics actors.
        /// </summary>
        private void ReleaseBodies(Rigidbody[] bodies, Collider[] colliders, Rigidbody grabBody, Transform playerRoot)
        {
            // The body hangs beside the player's CharacterController capsule;
            // it must never collide with it or the limbs snag on the invisible
            // capsule (and the dog must not feel the body at all)
            Collider[] playerColliders = playerRoot != null
                ? playerRoot.GetComponentsInChildren<Collider>(true)
                : System.Array.Empty<Collider>();

            foreach (var ragdollCollider in colliders)
            {
                foreach (var playerCollider in playerColliders)
                    Physics.IgnoreCollision(ragdollCollider, playerCollider, true);
            }

            var boneLookup = BuildTrackedBoneLookup();
            foreach (var body in bodies)
            {
                if (body == grabBody)
                    continue;

                // Gradual handover: each limb keeps the velocity it had in the
                // fall animation instead of popping to a dead stop
                body.linearVelocity = EstimateBoneVelocity(body.name, boneLookup);
                body.angularVelocity = Random.insideUnitSphere * randomTumble;
            }
        }

        // ------------------------------------------------------------------
        // Bone matching. The ragdoll skeleton prefixes bone names with "R_"
        // (R_Spine2, R_L Thigh, ...); match against the animated skeleton by
        // the normalized name so both naming schemes work.
        // ------------------------------------------------------------------

        private static string NormalizeBoneName(string name)
        {
            return name.StartsWith("R_") ? name.Substring(2) : name;
        }

        private Dictionary<string, int> BuildTrackedBoneLookup()
        {
            var lookup = new Dictionary<string, int>();
            for (int i = 0; i < trackedBones.Length; i++)
            {
                if (trackedBones[i] == null)
                    continue;
                string key = NormalizeBoneName(trackedBones[i].name);
                if (!lookup.ContainsKey(key))
                    lookup[key] = i;
            }
            return lookup;
        }

        private Vector3 EstimateBoneVelocity(string boneName, Dictionary<string, int> boneLookup)
        {
            if (!HasVelocityCapture || captureDeltaTime <= 0f)
                return Vector3.zero;
            if (!boneLookup.TryGetValue(NormalizeBoneName(boneName), out int index))
                return Vector3.zero;

            Vector3 velocity = (bonePositions[index] - prevBonePositions[index]) / captureDeltaTime;
            return Vector3.ClampMagnitude(velocity, boneVelocityClamp);
        }

        /// <summary>Poses the ragdoll skeleton to match the animated one.</summary>
        private static void CopyPose(Transform source, Transform target)
        {
            var sourceBones = new Dictionary<string, Transform>();
            foreach (var bone in source.GetComponentsInChildren<Transform>(true))
            {
                string key = NormalizeBoneName(bone.name);
                if (!sourceBones.ContainsKey(key))
                    sourceBones[key] = bone;
            }

            foreach (var bone in target.GetComponentsInChildren<Transform>(true))
            {
                if (bone == target)
                    continue;

                if (sourceBones.TryGetValue(NormalizeBoneName(bone.name), out var match))
                {
                    bone.localPosition = match.localPosition;
                    bone.localRotation = match.localRotation;
                }
            }
        }

        // Normalized bone names per limb, most-specific first. Every chain
        // additionally falls back to the spine (appended in ResolveLimbBody)
        // so a trimmed-down ragdoll variant still yields SOME pin.
        private static readonly Dictionary<DecoyLimb, string[]> LimbBoneChains = new Dictionary<DecoyLimb, string[]>
        {
            [DecoyLimb.RightForearm] = new[] { "R Forearm", "R Hand", "R UpperArm" },
            [DecoyLimb.LeftForearm] = new[] { "L Forearm", "L Hand", "L UpperArm" },
            [DecoyLimb.RightHand] = new[] { "R Hand", "R Forearm", "R UpperArm" },
            [DecoyLimb.LeftHand] = new[] { "L Hand", "L Forearm", "L UpperArm" },
            [DecoyLimb.RightUpperArm] = new[] { "R UpperArm", "R Forearm" },
            [DecoyLimb.LeftUpperArm] = new[] { "L UpperArm", "L Forearm" },
            [DecoyLimb.Head] = new[] { "Head", "Neck" },
            [DecoyLimb.Chest] = new[] { "Spine2", "Spine1", "CG" },
            [DecoyLimb.RightThigh] = new[] { "R Thigh", "R Calf" },
            [DecoyLimb.LeftThigh] = new[] { "L Thigh", "L Calf" },
            [DecoyLimb.RightCalf] = new[] { "R Calf", "R Thigh", "R Foot" },
            [DecoyLimb.LeftCalf] = new[] { "L Calf", "L Thigh", "L Foot" },
            [DecoyLimb.RightFoot] = new[] { "R Foot", "R Calf" },
            [DecoyLimb.LeftFoot] = new[] { "L Foot", "L Calf" },
        };

        /// <summary>The bone name a limb should ideally resolve to (no fallback).</summary>
        public static string PrimaryBoneName(DecoyLimb limb)
        {
            return LimbBoneChains.TryGetValue(limb, out var chain) ? chain[0] : "Spine2";
        }

        /// <summary>
        /// The rigidbody the mouth pin grabs for a limb, walking the limb's
        /// fallback chain and then the spine. Static so DecoySetup can validate
        /// full-limb coverage against the ragdoll prefab at build time.
        /// </summary>
        public static Rigidbody ResolveLimbBody(Transform ragdollRoot, DecoyLimb limb)
        {
            var bodies = ragdollRoot.GetComponentsInChildren<Rigidbody>(true);
            var chain = LimbBoneChains.TryGetValue(limb, out var names) ? names : System.Array.Empty<string>();

            foreach (string boneName in chain.Concat(new[] { "Spine2", "Spine1", "CG" }))
            {
                foreach (var body in bodies)
                {
                    if (NormalizeBoneName(body.name) == boneName)
                        return body;
                }
            }
            return null;
        }

        private void OnDestroy()
        {
            // The ragdoll and its anchor live under the dog's jaw once caught -
            // tear them down with the decoy so a chase cleanup can't orphan them
            if (mouthAnchor != null)
                Destroy(mouthAnchor.gameObject);
            else if (ragdollInstance != null)
                Destroy(ragdollInstance);
        }
    }
}
