using System.Collections.Generic;
using UnityEngine;

namespace RingSport.Level
{
    /// <summary>
    /// The human decoy actor: the Malbers placeholder human (Steve) with a
    /// runner-specific Animator (run / strafe-lean / fall-forward) and the
    /// catch handover for the flee attack - the animated model swaps to the
    /// Malbers Steve ragdoll, the RIGHT FOREARM is pinned kinematically to the
    /// dog's mouth (a sleeve-style grab), and every other joint keeps its
    /// animated pose and velocity so the body continues its fall and
    /// dangles/bounces off the ground. Also intended to host the decoy for the
    /// face attack and decoy battle mini levels. Prefab + Animator are
    /// generated by Tools > RingSport > Setup Decoy.
    /// </summary>
    public class DecoyController : MonoBehaviour
    {
        [SerializeField] private Animator animator;
        [Tooltip("Malbers 'Steve Ragdoll' prefab; the animated model swaps to it when caught.")]
        [SerializeField] private GameObject ragdollPrefab;

        [Header("Blend Damping")]
        [SerializeField] private float moveSpeedDampTime = 0.2f;
        [SerializeField] private float strafeDampTime = 0.12f;

        [Header("Catch Ragdoll")]
        [Tooltip("Ragdoll bone the dog's mouth grabs, by normalized name (the 'R_' rig prefix is ignored). Falls back through hand/upper arm/spine if missing.")]
        [SerializeField] private string grabBoneName = "R Forearm";
        [Tooltip("How far in front of the mouth bone the grabbed bone is pinned (along the dog model's forward).")]
        [SerializeField] private float grabForwardOffset = 0.2f;
        [SerializeField] private float grabUpOffset = 0.02f;
        [Tooltip("Cap on the per-bone velocity carried over from the animation into the ragdoll (m/s).")]
        [SerializeField] private float boneVelocityClamp = 8f;
        [Tooltip("Bounciness of the ragdoll limbs against the ground.")]
        [SerializeField] [Range(0f, 1f)] private float groundBounciness = 0.35f;
        [SerializeField] private float randomTumble = 1.5f;

        private static readonly int MoveSpeedHash = Animator.StringToHash("MoveSpeed");
        private static readonly int StrafeHash = Animator.StringToHash("Strafe");
        private static readonly int AnimSpeedHash = Animator.StringToHash("AnimSpeed");
        private static readonly int FallHash = Animator.StringToHash("Fall");

        // Previous-frame bone snapshot of the animated model, for the
        // animation -> physics velocity handover at the catch
        private Transform[] trackedBones = System.Array.Empty<Transform>();
        private Vector3[] bonePositions = System.Array.Empty<Vector3>();
        private Vector3[] prevBonePositions = System.Array.Empty<Vector3>();
        private float captureDeltaTime;
        private int captureCount;

        // Velocities need positions from two frames
        private bool HasVelocityCapture => captureCount >= 2;

        private GameObject ragdollInstance;
        private Transform mouthAnchor;
        private PhysicsMaterial bounceMaterial;
        private float modelScale = 1f;

        public bool IsCarried { get; private set; }

        /// <summary>Exposed so the scene warm-up can pre-deserialize it.</summary>
        public GameObject RagdollPrefab => ragdollPrefab;

        private void Awake()
        {
            if (animator == null)
                animator = GetComponentInChildren<Animator>(true);

            if (animator != null)
            {
                // Same constraints as the dog: unscaled time so freezes can't
                // stall one-shots, no root motion so code owns all travel.
                animator.updateMode = AnimatorUpdateMode.UnscaledTime;
                animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
                animator.applyRootMotion = false;

                trackedBones = animator.GetComponentsInChildren<Transform>(true);
                bonePositions = new Vector3[trackedBones.Length];
                prevBonePositions = new Vector3[trackedBones.Length];

                // The model is scaled up in the prefab; stride length scales
                // with it, so locomotion cycles slow down by the same factor to
                // keep the feet in sync with the same world scroll speed
                modelScale = Mathf.Max(0.01f, animator.transform.lossyScale.z);
            }
        }

        /// <summary>
        /// moveSpeed: 0 = idle, 1 = jog, 2 = sprint. strafe: -1..1 lane-change
        /// lean. animSpeed: playback multiplier on the locomotion cycle.
        /// </summary>
        public void UpdateLocomotion(float moveSpeed, float strafe, float animSpeed, float deltaTime)
        {
            if (animator == null || IsCarried)
                return;

            animator.SetFloat(MoveSpeedHash, moveSpeed, moveSpeedDampTime, deltaTime);
            animator.SetFloat(StrafeHash, Mathf.Clamp(strafe, -1f, 1f), strafeDampTime, deltaTime);
            animator.SetFloat(AnimSpeedHash, animSpeed / modelScale);
        }

        /// <summary>Fall-forward one-shot, fired when the dog pounces.</summary>
        public void TriggerFall()
        {
            if (animator == null || IsCarried)
                return;

            // The fall clip carries its drop/stumble in root motion; let it own
            // the model's local travel for the topple (locomotion keeps root
            // motion off so code owns all travel while running)
            animator.applyRootMotion = true;
            animator.SetTrigger(FallHash);
        }

        private void LateUpdate()
        {
            if (IsCarried || animator == null)
                return;

            // Snapshot bone positions after animation so the catch can compute
            // per-bone velocities from the last two frames
            float dt = Time.deltaTime;
            if (dt <= 0f)
                return;

            var swap = prevBonePositions;
            prevBonePositions = bonePositions;
            bonePositions = swap;
            for (int i = 0; i < trackedBones.Length; i++)
                bonePositions[i] = trackedBones[i] != null ? trackedBones[i].position : Vector3.zero;

            captureDeltaTime = dt;
            captureCount++;
        }

        /// <summary>
        /// The catch: swaps the animated model for the ragdoll mid-pose, snaps
        /// the right forearm to the mouth bone (kinematic, parented under it -
        /// no force path back into the dog, a sleeve-style grab), and lets
        /// every other joint continue the fall with its animated velocity so
        /// the body dangles and bounces off the ground during the carry.
        /// </summary>
        public void AttachToMouth(Transform mouth, Vector3 carryForward, Transform playerRoot)
        {
            if (IsCarried || mouth == null)
                return;

            IsCarried = true;

            Transform model = animator != null ? animator.transform : transform;
            Vector3 grabTarget = mouth.position + carryForward.normalized * grabForwardOffset + Vector3.up * grabUpOffset;

            if (ragdollPrefab == null)
            {
                // No ragdoll available - carry the whole animated model like the
                // old sphere did, frozen in its fall pose
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }

            ragdollInstance = Instantiate(ragdollPrefab, model.position, model.rotation);
            ragdollInstance.name = "DecoyRagdoll";
            // The animated model is scaled up in the prefab; the ragdoll must
            // match or the pose copy lands on a smaller skeleton
            ragdollInstance.transform.localScale = model.lossyScale;

            // Strip the Malbers behaviours; joints, rigidbodies and colliders stay
            foreach (var behaviour in ragdollInstance.GetComponentsInChildren<MonoBehaviour>(true))
                Destroy(behaviour);
            foreach (var anim in ragdollInstance.GetComponentsInChildren<Animator>(true))
                anim.enabled = false;

            CopyPose(model, ragdollInstance.transform);

            var grabBody = FindGrabBody(ragdollInstance.transform);
            if (grabBody == null)
            {
                // Should never happen with the Malbers ragdoll (R_R Forearm has
                // a rigidbody) - fall back to the whole-model carry
                Debug.LogWarning("[DecoyController] No grab rigidbody found in the ragdoll - carrying the animated model instead.");
                Destroy(ragdollInstance);
                ragdollInstance = null;
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }

            // Snap: rigid-translate the whole posed ragdoll so the grabbed arm
            // lands in the mouth, keeping the mid-fall orientation for continuity
            ragdollInstance.transform.position += grabTarget - grabBody.transform.position;

            // Anchor under the mouth bone; the kinematic grabbed bone is
            // parented to it so it rigidly follows the head animation.
            // Kinematic = infinite mass, so nothing the body does can push the
            // dog around.
            mouthAnchor = new GameObject("DecoyMouthAnchor").transform;
            mouthAnchor.position = grabBody.transform.position;
            mouthAnchor.rotation = grabBody.transform.rotation;
            mouthAnchor.SetParent(mouth, true);

            ragdollInstance.transform.SetParent(mouthAnchor, true);
            grabBody.transform.SetParent(mouthAnchor, true);

            SetupBodies(grabBody, playerRoot);

            // The animated model's job is done
            model.gameObject.SetActive(false);
        }

        private void SetupBodies(Rigidbody grabBody, Transform playerRoot)
        {
            var boneLookup = BuildTrackedBoneLookup();

            // The corpse hangs beside the player's CharacterController capsule;
            // it must never collide with it or the limbs snag on the invisible
            // capsule (and the dog must not feel the body at all)
            Collider[] playerColliders = playerRoot != null
                ? playerRoot.GetComponentsInChildren<Collider>(true)
                : System.Array.Empty<Collider>();

            if (bounceMaterial == null)
            {
                bounceMaterial = new PhysicsMaterial("DecoyBounce")
                {
                    bounciness = groundBounciness,
                    bounceCombine = PhysicsMaterialCombine.Maximum,
                    dynamicFriction = 0.5f,
                    staticFriction = 0.5f
                };
            }

            foreach (var ragdollCollider in ragdollInstance.GetComponentsInChildren<Collider>(true))
            {
                ragdollCollider.sharedMaterial = bounceMaterial;
                foreach (var playerCollider in playerColliders)
                    Physics.IgnoreCollision(ragdollCollider, playerCollider, true);
            }

            // Joint projection snaps drifting limbs back to their sockets - the
            // main anti-twitch (same treatment as PlayerRagdoll)
            foreach (var joint in ragdollInstance.GetComponentsInChildren<CharacterJoint>(true))
            {
                joint.enableProjection = true;
                joint.projectionDistance = 0.05f;
                joint.projectionAngle = 30f;
            }

            foreach (var body in ragdollInstance.GetComponentsInChildren<Rigidbody>(true))
            {
                if (body == grabBody)
                {
                    // Kinematic bodies don't support continuous collision
                    body.collisionDetectionMode = CollisionDetectionMode.Discrete;
                    body.isKinematic = true;
                    continue;
                }

                body.isKinematic = false;
                body.useGravity = true;
                body.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
                body.interpolation = RigidbodyInterpolation.Interpolate;
                body.solverIterations = 8;
                body.sleepThreshold = 0.05f;

                // Gradual handover: each limb keeps the velocity it had in the
                // fall animation instead of popping to a dead stop
                body.linearVelocity = EstimateBoneVelocity(body.name, boneLookup);
                body.angularVelocity = Random.insideUnitSphere * randomTumble;
            }
        }

        // ------------------------------------------------------------------
        // Bone matching. The ragdoll skeleton prefixes bone names with "R_"
        // (R_Spine2, R_L Thigh, ...); match against the animated skeleton by
        // the normalized name so both naming schemes work.
        // ------------------------------------------------------------------

        private static string NormalizeBoneName(string name)
        {
            return name.StartsWith("R_") ? name.Substring(2) : name;
        }

        private Dictionary<string, int> BuildTrackedBoneLookup()
        {
            var lookup = new Dictionary<string, int>();
            for (int i = 0; i < trackedBones.Length; i++)
            {
                if (trackedBones[i] == null)
                    continue;
                string key = NormalizeBoneName(trackedBones[i].name);
                if (!lookup.ContainsKey(key))
                    lookup[key] = i;
            }
            return lookup;
        }

        private Vector3 EstimateBoneVelocity(string boneName, Dictionary<string, int> boneLookup)
        {
            if (!HasVelocityCapture || captureDeltaTime <= 0f)
                return Vector3.zero;
            if (!boneLookup.TryGetValue(NormalizeBoneName(boneName), out int index))
                return Vector3.zero;

            Vector3 velocity = (bonePositions[index] - prevBonePositions[index]) / captureDeltaTime;
            return Vector3.ClampMagnitude(velocity, boneVelocityClamp);
        }

        /// <summary>Poses the ragdoll skeleton to match the animated one.</summary>
        private static void CopyPose(Transform source, Transform target)
        {
            var sourceBones = new Dictionary<string, Transform>();
            foreach (var bone in source.GetComponentsInChildren<Transform>(true))
            {
                string key = NormalizeBoneName(bone.name);
                if (!sourceBones.ContainsKey(key))
                    sourceBones[key] = bone;
            }

            foreach (var bone in target.GetComponentsInChildren<Transform>(true))
            {
                if (bone == target)
                    continue;

                if (sourceBones.TryGetValue(NormalizeBoneName(bone.name), out var match))
                {
                    bone.localPosition = match.localPosition;
                    bone.localRotation = match.localRotation;
                }
            }
        }

        /// <summary>
        /// The rigidbody the mouth pin grabs: the configured bone (right
        /// forearm by default - a sleeve grab), falling back through the rest
        /// of the arm and the spine if the ragdoll variant lacks one there.
        /// </summary>
        private Rigidbody FindGrabBody(Transform ragdollRoot)
        {
            var bodies = ragdollRoot.GetComponentsInChildren<Rigidbody>(true);
            foreach (string boneName in new[] { grabBoneName, "R Hand", "R UpperArm", "Spine2", "Spine1" })
            {
                if (string.IsNullOrEmpty(boneName))
                    continue;
                foreach (var body in bodies)
                {
                    if (NormalizeBoneName(body.name) == boneName)
                        return body;
                }
            }
            return null;
        }

        private void OnDestroy()
        {
            // The ragdoll and its anchor live under the dog's jaw once caught -
            // tear them down with the decoy so a chase cleanup can't orphan them
            if (mouthAnchor != null)
                Destroy(mouthAnchor.gameObject);
            else if (ragdollInstance != null)
                Destroy(ragdollInstance);
        }
    }
}
