using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using RingSport.Core;

namespace RingSport.Level
{
    /// <summary>
    /// Body parts the dog's pounce can grab on the decoy ragdoll. Every value
    /// maps to a bone with its own rigidbody on the generated decoy ragdoll
    /// (validated by DecoySetup at build time), so any of them can be the
    /// kinematic mouth pin: flee attack takes the right forearm, the face
    /// attack will take the head, etc.
    /// </summary>
    public enum DecoyLimb
    {
        RightForearm,
        LeftForearm,
        RightHand,
        LeftHand,
        RightUpperArm,
        LeftUpperArm,
        Head,
        Chest,
        RightThigh,
        LeftThigh,
        RightCalf,
        LeftCalf,
        RightFoot,
        LeftFoot,
    }

    /// <summary>
    /// The human decoy actor: the decoy model (Assets/Models/decoy.glb, rigged
    /// on the Malbers human skeleton and animated through a generated Humanoid
    /// avatar) with a runner-specific Animator (run / strafe-lean /
    /// fall-forward) and the catch handover for the flee attack - the animated
    /// model swaps to the generated decoy ragdoll, the RIGHT FOREARM is pinned
    /// kinematically to the dog's mouth (a sleeve-style grab), and every other
    /// joint keeps its animated pose and velocity so the body continues its
    /// fall and dangles/bounces off the ground. The ragdoll's joint frames and
    /// masses are rebuilt on the way in (see ConfigureBodies) so the limbs
    /// cannot corkscrew and the weight sits in the torso. Also hosts the decoy
    /// for the face attack. Prefab, avatar, ragdoll and Animator are all
    /// generated by Tools > RingSport > Setup Decoy.
    /// </summary>
    public class DecoyController : MonoBehaviour
    {
        [SerializeField] private Animator animator;
        [Tooltip("Generated DecoyRagdoll prefab; the animated model swaps to it when caught.")]
        [SerializeField] private GameObject ragdollPrefab;

        [Header("Blend Damping")]
        [SerializeField] private float moveSpeedDampTime = 0.2f;
        [SerializeField] private float strafeDampTime = 0.12f;

        [Header("Catch Ragdoll")]
        [Tooltip("Limb the dog's mouth grabs when AttachToMouth is called without an explicit target (flee attack = sleeve-style right forearm).")]
        [SerializeField] private DecoyLimb defaultGrabLimb = DecoyLimb.RightForearm;
        [Tooltip("TESTING: each catch without an explicit target grabs a random arm/leg limb instead of the default, so every grab point gets exercised. Head/torso are excluded - they still ragdoll.")]
        [SerializeField] private bool randomizeGrabLimb = true;
        [Tooltip("How far in front of the mouth bone the grabbed bone is pinned (along the dog model's forward).")]
        [SerializeField] private float grabForwardOffset = 0.2f;
        [SerializeField] private float grabUpOffset = 0.02f;
        [Tooltip("Seconds over which the grabbed limb settles from where the bite lands into the mouth offset. The dog steers onto the limb during the pounce, so this only covers the last few centimeters.")]
        [SerializeField] private float grabBlendSeconds = 0.1f;
        [Tooltip("Cap on the per-bone velocity carried over from the animation into the ragdoll (m/s).")]
        [SerializeField] private float boneVelocityClamp = 8f;
        [Tooltip("Bounciness of the ragdoll limbs against the ground.")]
        [SerializeField] [Range(0f, 1f)] private float groundBounciness = 0.35f;
        [SerializeField] private float randomTumble = 1.5f;

        [Header("Carry Clearance")]
        [Tooltip("Sideways kick given to the body at the bite, so it clears the dog straight away instead of waiting for the hang to swing it out (m/s). The side is picked from where the bite lands - see ResolveCarrySide.")]
        [SerializeField] private float carrySideImpulse = 1.2f;
        [Tooltip("Sideways acceleration held for the rest of the carry (m/s^2, against gravity's 9.8). This is what sets the angle the body hangs at - roughly atan(this/9.8) off vertical - so it keeps clear of the dog instead of drifting back through it. 0 disables the clearance push.")]
        [SerializeField] private float carrySideAcceleration = 4f;

        [Header("Ragdoll Weight")]
        [Tooltip("Mass multiplier on the pelvis/spine bodies. The Malbers ragdoll gives the torso less mass than the legs, so whichever limb is in the dog's mouth whips the body around. Loading up the middle makes the torso the thing that drags and the limbs the things that follow.")]
        [SerializeField] private float torsoMassMultiplier = 4f;
        [Tooltip("Mass multiplier on the arm and leg bodies. Light limbs trail behind the heavy torso instead of driving it.")]
        [SerializeField] private float limbMassMultiplier = 0.6f;
        [Tooltip("Angular damping on the limbs - higher means they swing lazily behind the body rather than spinning freely.")]
        [SerializeField] private float limbAngularDamping = 4f;
        [Tooltip("Angular damping on the torso. Kept lower than the limbs so the body still rolls as it is dragged.")]
        [SerializeField] private float torsoAngularDamping = 1.5f;
        [Tooltip("Linear damping on every body - a little air resistance keeps the trailing limbs from overshooting.")]
        [SerializeField] private float linearDamping = 0.1f;

        [Header("Ragdoll Joints")]
        [Tooltip("Replace the package's joint limits with anatomical ones measured off the rig, the same treatment the dog's ragdoll gets in CaicosRagdollSetup. Off = keep the Malbers limits, which let the shoulders, hips and spine corkscrew.")]
        [SerializeField] private bool tightenJointLimits = true;

        private static readonly int MoveSpeedHash = Animator.StringToHash("MoveSpeed");
        private static readonly int StrafeHash = Animator.StringToHash("Strafe");
        private static readonly int AnimSpeedHash = Animator.StringToHash("AnimSpeed");
        private static readonly int FallHash = Animator.StringToHash("Fall");
        private static readonly int PowerUpHash = Animator.StringToHash("PowerUp");
        private static readonly int LocomotionStateHash = Animator.StringToHash("Locomotion");

        // Whether the generated controller has the PowerUp trigger (guards
        // against a stale pre-v11 controller so SetTrigger never warns)
        private bool? hasPowerUpParam;

        // Previous-frame bone snapshot of the animated model, for the
        // animation -> physics velocity handover at the catch
        private Transform[] trackedBones = System.Array.Empty<Transform>();
        private Vector3[] bonePositions = System.Array.Empty<Vector3>();
        private Vector3[] prevBonePositions = System.Array.Empty<Vector3>();
        private float captureDeltaTime;
        private int captureCount;

        // Velocities need positions from two frames
        private bool HasVelocityCapture => captureCount >= 2;

        private GameObject ragdollInstance;
        private Transform mouthAnchor;
        private PhysicsMaterial bounceMaterial;
        private float modelScale = 1f;
        private bool limbChosen;
        private Transform pendingGrabBone;

        // Carry clearance: the free bodies the sideways push applies to (the
        // kinematic mouth pin is excluded), which way it pushes (+1 = the dog's
        // right), and the lateral axis - kept in the player root's local space
        // so it follows the dog rather than a stale world direction
        private Rigidbody[] carriedBodies = System.Array.Empty<Rigidbody>();
        private Transform carryRoot;
        private Vector3 carryLateral = Vector3.right;
        private float carrySide;

        public bool IsCarried { get; private set; }

        /// <summary>
        /// The limb the catch will grab, decided when the pounce fires (so the
        /// dog can steer its leap onto it before the bite).
        /// </summary>
        public DecoyLimb PendingGrabLimb { get; private set; }

        /// <summary>Exposed so the scene warm-up can pre-deserialize it.</summary>
        public GameObject RagdollPrefab => ragdollPrefab;

        private void Awake()
        {
            if (animator == null)
                animator = GetComponentInChildren<Animator>(true);

            if (animator != null)
            {
                // Same constraints as the dog: unscaled time so freezes can't
                // stall one-shots, no root motion so code owns all travel.
                animator.updateMode = AnimatorUpdateMode.UnscaledTime;
                animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
                animator.applyRootMotion = false;

                trackedBones = animator.GetComponentsInChildren<Transform>(true);
                bonePositions = new Vector3[trackedBones.Length];
                prevBonePositions = new Vector3[trackedBones.Length];

                // The model is scaled up in the prefab; stride length scales
                // with it, so locomotion cycles slow down by the same factor to
                // keep the feet in sync with the same world scroll speed
                modelScale = Mathf.Max(0.01f, animator.transform.lossyScale.z);
            }
        }

        /// <summary>
        /// moveSpeed: 0 = idle, 1 = jog, 2 = sprint. strafe: -1..1 lane-change
        /// lean. animSpeed: playback multiplier on the locomotion cycle.
        /// </summary>
        public void UpdateLocomotion(float moveSpeed, float strafe, float animSpeed, float deltaTime)
        {
            if (animator == null || IsCarried)
                return;

            animator.SetFloat(MoveSpeedHash, moveSpeed, moveSpeedDampTime, deltaTime);
            animator.SetFloat(StrafeHash, Mathf.Clamp(strafe, -1f, 1f), strafeDampTime, deltaTime);
            animator.SetFloat(AnimSpeedHash, animSpeed / modelScale);
        }

        /// <summary>
        /// Fall-forward one-shot, fired when the dog pounces. Also locks in the
        /// grab limb so the pounce can steer toward it - the catch then grabs
        /// the same limb.
        /// </summary>
        public void TriggerFall()
        {
            TriggerFall(randomizeGrabLimb
                ? RandomLimbPool[Random.Range(0, RandomLimbPool.Length)]
                : defaultGrabLimb);
        }

        /// <summary>
        /// Fall-forward one-shot with an explicit grab target - the face attack
        /// passes the limb the player picked in its quick time event.
        /// </summary>
        public void TriggerFall(DecoyLimb limb)
        {
            if (animator == null || IsCarried)
                return;

            PendingGrabLimb = limb;
            limbChosen = true;
            pendingGrabBone = FindTrackedBone(PrimaryBoneName(limb));
            GameLog.Info($"[DecoyController] Pounce target: {PendingGrabLimb}");

            // The fall clip carries its drop/stumble in root motion; let it own
            // the model's local travel for the topple (locomotion keeps root
            // motion off so code owns all travel while running)
            animator.applyRootMotion = true;
            animator.SetTrigger(FallHash);
        }

        /// <summary>
        /// Arms-up power-up taunt: the face attack fires this as the decoy
        /// squares up, so the frozen QTE holds an aggressive pose with the
        /// limb targets spread wide. No-ops gracefully on a stale controller.
        /// </summary>
        public void TriggerPowerUp()
        {
            if (animator == null || IsCarried || !HasPowerUpParam)
                return;
            animator.SetTrigger(PowerUpHash);
        }

        /// <summary>
        /// Blends a one-shot pose (the power-up taunt) back into the
        /// locomotion blend - the dodge escape bolts mid-pose.
        /// </summary>
        public void ResumeLocomotion()
        {
            if (animator == null || IsCarried)
                return;
            if (HasPowerUpParam)
                animator.ResetTrigger(PowerUpHash);
            animator.CrossFadeInFixedTime(LocomotionStateHash, 0.2f, 0);
        }

        private bool HasPowerUpParam
        {
            get
            {
                if (!hasPowerUpParam.HasValue)
                {
                    hasPowerUpParam = false;
                    if (animator != null)
                    {
                        foreach (var parameter in animator.parameters)
                        {
                            if (parameter.nameHash == PowerUpHash)
                            {
                                hasPowerUpParam = true;
                                break;
                            }
                        }
                    }
                }
                return hasPowerUpParam.Value;
            }
        }

        /// <summary>
        /// World position of a limb's bone on the ANIMATED model - the anchor
        /// the face attack's screen-space tap targets track each frame.
        /// </summary>
        public Vector3 GetLimbPosition(DecoyLimb limb)
        {
            Transform bone = FindTrackedBone(PrimaryBoneName(limb));
            if (bone != null)
                return bone.position;
            Transform model = animator != null ? animator.transform : transform;
            return model.position + Vector3.up * 0.8f * modelScale;
        }

        /// <summary>
        /// World position of the pending grab limb's bone on the ANIMATED model
        /// (valid during the fall, before the ragdoll swap) - the point the
        /// dog's pounce steers its mouth onto.
        /// </summary>
        public Vector3 GetGrabLimbPosition()
        {
            if (pendingGrabBone != null)
                return pendingGrabBone.position;
            Transform model = animator != null ? animator.transform : transform;
            return model.position + Vector3.up * 0.8f * modelScale;
        }

        private Transform FindTrackedBone(string normalizedName)
        {
            foreach (var bone in trackedBones)
            {
                if (bone != null && NormalizeBoneName(bone.name) == normalizedName)
                    return bone;
            }
            return null;
        }

        private void LateUpdate()
        {
            if (IsCarried || animator == null)
                return;

            // Snapshot bone positions after animation so the catch can compute
            // per-bone velocities from the last two frames
            float dt = Time.deltaTime;
            if (dt <= 0f)
                return;

            var swap = prevBonePositions;
            prevBonePositions = bonePositions;
            bonePositions = swap;
            for (int i = 0; i < trackedBones.Length; i++)
                bonePositions[i] = trackedBones[i] != null ? trackedBones[i].position : Vector3.zero;

            captureDeltaTime = dt;
            captureCount++;
        }

        // Arms and legs only - the head and chest grabs exist for the future
        // face attack etc., which pass their limb explicitly
        private static readonly DecoyLimb[] RandomLimbPool =
        {
            DecoyLimb.RightForearm, DecoyLimb.LeftForearm,
            DecoyLimb.RightHand, DecoyLimb.LeftHand,
            DecoyLimb.RightUpperArm, DecoyLimb.LeftUpperArm,
            DecoyLimb.RightThigh, DecoyLimb.LeftThigh,
            DecoyLimb.RightCalf, DecoyLimb.LeftCalf,
            DecoyLimb.RightFoot, DecoyLimb.LeftFoot,
        };

        /// <summary>
        /// Catch using the limb the pounce aimed at (locked in by TriggerFall),
        /// falling back to the default/randomized choice for callers that
        /// never pounced.
        /// </summary>
        public void AttachToMouth(Transform mouth, Vector3 carryForward, Transform playerRoot)
        {
            DecoyLimb limb = limbChosen
                ? PendingGrabLimb
                : randomizeGrabLimb
                    ? RandomLimbPool[Random.Range(0, RandomLimbPool.Length)]
                    : defaultGrabLimb;
            AttachToMouth(mouth, carryForward, playerRoot, limb);
        }

        /// <summary>
        /// The catch: swaps the animated model for the ragdoll mid-pose, snaps
        /// the targeted limb to the mouth bone (kinematic, parented under it -
        /// no force path back into the dog), and lets every other joint
        /// continue the fall with its animated velocity so the body dangles
        /// and bounces off the ground during the carry. The body is also
        /// leaned out to whichever side of the mouth it landed on so it hangs
        /// beside the dog rather than through it (see ResolveCarrySide). Any
        /// DecoyLimb can be the pin - future mini levels (face attack, decoy
        /// battle) pass their own target.
        /// </summary>
        public void AttachToMouth(Transform mouth, Vector3 carryForward, Transform playerRoot, DecoyLimb limb)
        {
            if (IsCarried || mouth == null)
                return;

            IsCarried = true;

            Transform model = animator != null ? animator.transform : transform;
            Vector3 grabTarget = mouth.position + carryForward.normalized * grabForwardOffset + Vector3.up * grabUpOffset;

            if (ragdollPrefab == null)
            {
                // No ragdoll available - carry the whole animated model like the
                // old sphere did, frozen in its fall pose
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }

            // Spawn under an INACTIVE holder: joints capture their physics
            // frames the moment an active instance awakes, so the scale, pose
            // and kinematic flags must all be final BEFORE activation. Scaling
            // an already-awake ragdoll leaves every joint solving against
            // stale scale-1 anchors (the "detached ragdoll" bug).
            var spawnHolder = new GameObject("DecoyRagdollSpawn");
            spawnHolder.SetActive(false);
            ragdollInstance = Instantiate(ragdollPrefab, model.position, model.rotation, spawnHolder.transform);
            ragdollInstance.name = "DecoyRagdoll";
            ragdollInstance.transform.localScale = model.lossyScale;

            // Strip the Malbers behaviours; joints, rigidbodies and colliders stay
            foreach (var behaviour in ragdollInstance.GetComponentsInChildren<MonoBehaviour>(true))
                Destroy(behaviour);
            foreach (var anim in ragdollInstance.GetComponentsInChildren<Animator>(true))
                anim.enabled = false;

            // Gather the physics pieces NOW - the grabbed limb's subtree is
            // reparented out of this hierarchy below, and a later
            // GetComponentsInChildren would silently skip it (which previously
            // left the pin dynamic: nothing actually held the body)
            var bodies = ragdollInstance.GetComponentsInChildren<Rigidbody>(true);
            var colliders = ragdollInstance.GetComponentsInChildren<Collider>(true);
            var joints = ragdollInstance.GetComponentsInChildren<CharacterJoint>(true);

            CopyPose(model, ragdollInstance.transform);

            var grabBody = ResolveLimbBody(ragdollInstance.transform, limb);
            if (grabBody == null)
            {
                // Should never happen with the generated ragdoll (every
                // DecoyLimb maps to a rigidbody) - fall back to the whole-model carry
                GameLog.Warn($"[DecoyController] No rigidbody found for limb {limb} in the ragdoll - carrying the animated model instead.");
                Destroy(spawnHolder);
                ragdollInstance = null;
                transform.position = grabTarget;
                transform.SetParent(mouth, true);
                return;
            }

            // Which way to hold the body clear of the dog, decided from the
            // pose the bite lands in and then held for the whole carry
            // (FixedUpdate). The lateral axis comes off the carry forward - the
            // dog's body runs back from the mouth along it, so perpendicular is
            // the way out - and is stored player-local so it turns with the dog.
            Vector3 flatForward = Vector3.ProjectOnPlane(carryForward, Vector3.up);
            Vector3 lateralWorld = flatForward.sqrMagnitude > 1e-6f
                ? Vector3.Cross(Vector3.up, flatForward).normalized
                : Vector3.right;
            carrySide = ResolveCarrySide(grabBody, playerRoot, lateralWorld);
            carryRoot = playerRoot;
            carryLateral = playerRoot != null
                ? playerRoot.InverseTransformDirection(lateralWorld)
                : lateralWorld;
            carriedBodies = bodies.Where(body => body != null && body != grabBody).ToArray();

            GameLog.Info($"[DecoyController] Pounce grab: {limb} -> {grabBody.name}, carried off the dog's {(carrySide > 0f ? "right" : "left")}");

            ConfigureBodies(bodies, colliders, joints, grabBody);

            // Anchor under the mouth bone; the kinematic grabbed bone is
            // parented to it so it rigidly follows the head animation.
            // Kinematic = infinite mass, so nothing the body does can push the
            // dog around. The anchor starts at the limb's CURRENT position -
            // the body stays exactly where the bite visually lands - and is
            // then yanked into the mouth over grabBlendSeconds (an instant
            // snap teleports the whole body by up to a limb's length).
            mouthAnchor = new GameObject("DecoyMouthAnchor").transform;
            mouthAnchor.position = grabBody.transform.position;
            mouthAnchor.rotation = grabBody.transform.rotation;
            mouthAnchor.SetParent(mouth, true);

            // Reparenting out of the inactive holder ACTIVATES the ragdoll -
            // physics wakes here, with final scale, pose and kinematic flags
            ragdollInstance.transform.SetParent(mouthAnchor, true);
            grabBody.transform.SetParent(mouthAnchor, true);
            Destroy(spawnHolder);

            ReleaseBodies(bodies, colliders, grabBody, playerRoot);

            StartCoroutine(BlendGrabToMouth(mouth.InverseTransformPoint(grabTarget)));

            // The animated model's job is done
            model.gameObject.SetActive(false);
        }

        /// <summary>
        /// Pulls the mouth anchor (and the kinematic limb pinned to it) from
        /// where the bite landed into the mouth, in jaw-local space so it
        /// keeps riding the head animation while it blends. The joints drag
        /// the rest of the body along, so the whole snatch reads as motion.
        /// </summary>
        private IEnumerator BlendGrabToMouth(Vector3 targetLocalPosition)
        {
            Vector3 startLocalPosition = mouthAnchor.localPosition;
            float elapsed = 0f;
            while (elapsed < grabBlendSeconds && mouthAnchor != null)
            {
                elapsed += Time.deltaTime;
                float k = Mathf.Clamp01(elapsed / grabBlendSeconds);
                k = k * k * (3f - 2f * k);
                mouthAnchor.localPosition = Vector3.Lerp(startLocalPosition, targetLocalPosition, k);
                yield return null;
            }
            if (mouthAnchor != null)
                mouthAnchor.localPosition = targetLocalPosition;
        }

        // ------------------------------------------------------------------
        // Carry clearance. The ragdoll's colliders ignore the dog's (see
        // ReleaseBodies), so nothing stops the body hanging straight down the
        // dog's centre line and drawing through the model. Leaning it out to
        // one side fixes that, and doing it as an acceleration rather than a
        // one-off shove is what makes it hold: the body is a pendulum swinging
        // off the jaw, so a kick alone just swings back through the dog.
        // ------------------------------------------------------------------

        /// <summary>
        /// Which side of the dog the caught body gets pushed toward: the side
        /// it is ALREADY on when the bite lands, so the push is the shortest
        /// way out from under the dog rather than a swing across it. Measured
        /// first off the grab point (the mouth pin is the pivot the body hangs
        /// from), then off the dog's centre line for grabs that land square -
        /// a head or chest bite has no torso offset to read. +1 = the dog's
        /// right.
        /// </summary>
        private float ResolveCarrySide(Rigidbody grabBody, Transform playerRoot, Vector3 lateralWorld)
        {
            // Under this it is bone jitter rather than a side
            float deadzone = 0.03f * modelScale;

            Transform torso = FindDescendant(ragdollInstance.transform, "Spine1")
                              ?? FindDescendant(ragdollInstance.transform, "CG");
            if (torso != null)
            {
                float hang = Vector3.Dot(torso.position - grabBody.transform.position, lateralWorld);
                if (Mathf.Abs(hang) > deadzone)
                    return Mathf.Sign(hang);
            }

            if (playerRoot != null)
            {
                float offset = Vector3.Dot(grabBody.transform.position - playerRoot.position, lateralWorld);
                if (Mathf.Abs(offset) > deadzone)
                    return Mathf.Sign(offset);
            }

            // Dead centre: either side clears the dog, so take one
            return 1f;
        }

        /// <summary>Current world lateral axis, following the dog as it turns.</summary>
        private Vector3 CarryLateralWorld()
        {
            return carryRoot != null ? carryRoot.TransformDirection(carryLateral) : carryLateral;
        }

        /// <summary>
        /// Holds the hang angle for the length of the carry. Applied as an
        /// acceleration so it reads as gravity tilted a few degrees sideways -
        /// every bone leans by the same amount whatever the mass profile did,
        /// and the pose stays the pose.
        /// </summary>
        private void FixedUpdate()
        {
            if (!IsCarried || carrySide == 0f || carrySideAcceleration <= 0f)
                return;

            Vector3 push = CarryLateralWorld() * (carrySide * carrySideAcceleration);
            foreach (var body in carriedBodies)
            {
                if (body != null && !body.isKinematic)
                    body.AddForce(push, ForceMode.Acceleration);
            }
        }

        /// <summary>Pre-activation physics setup - flags apply when the bodies wake.</summary>
        private void ConfigureBodies(Rigidbody[] bodies, Collider[] colliders, CharacterJoint[] joints, Rigidbody grabBody)
        {
            if (bounceMaterial == null)
            {
                bounceMaterial = new PhysicsMaterial("DecoyBounce")
                {
                    bounciness = groundBounciness,
                    bounceCombine = PhysicsMaterialCombine.Maximum,
                    dynamicFriction = 0.5f,
                    staticFriction = 0.5f
                };
            }

            foreach (var ragdollCollider in colliders)
                ragdollCollider.sharedMaterial = bounceMaterial;

            // Joint projection snaps drifting limbs back to their sockets - the
            // main anti-twitch (same treatment as PlayerRagdoll)
            foreach (var joint in joints)
            {
                joint.enableProjection = true;
                joint.projectionDistance = 0.05f;
                joint.projectionAngle = 30f;
                // Preprocessing lets the solver take shortcuts that go wrong
                // when a chain spans a big mass ratio - here a kinematic
                // (infinite mass) limb pinned to the jaw, then a light hand,
                // then the loaded-up torso
                joint.enablePreprocessing = false;

                if (tightenJointLimits)
                    TightenJoint(joint, ragdollInstance != null ? ragdollInstance.transform : null);
            }

            foreach (var body in bodies)
            {
                // Torso heavy, limbs light. Multipliers rather than absolute
                // masses so the package's own proportions inside each group
                // (thigh > calf > foot) survive.
                bool torso = IsTorsoBone(body.name);
                body.mass *= MassMultiplierFor(body.name);
                body.linearDamping = linearDamping;
                body.angularDamping = torso ? torsoAngularDamping : limbAngularDamping;

                if (body == grabBody)
                {
                    // Kinematic bodies don't support continuous collision
                    body.collisionDetectionMode = CollisionDetectionMode.Discrete;
                    body.isKinematic = true;
                    continue;
                }

                body.isKinematic = false;
                body.useGravity = true;
                body.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
                body.interpolation = RigidbodyInterpolation.Interpolate;
                // The heavy torso hanging off a light pinned limb needs more
                // solver passes than the free-falling dog corpse does
                body.solverIterations = 12;
                body.solverVelocityIterations = 4;
                body.sleepThreshold = 0.05f;
            }
        }

        // ------------------------------------------------------------------
        // Weight distribution and joint limits.
        //
        // The Malbers ragdoll is built for a body that falls over on the spot:
        // near-uniform masses, and joint frames whose TWIST axis is the bend
        // axis with the remaining swing left wide (shoulders and hips get 70
        // degrees of twist and 50 of swing, with the third axis pinned at a
        // degenerate 0 that the solver only honours softly). Dragged along the
        // ground by one limb that is pinned to the dog's jaw, that reads as a
        // rag: the arms and legs corkscrew past anything a body can do, and the
        // light torso gets flung by whichever limb is in the mouth.
        //
        // Both are fixed the way CaicosRagdollSetup fixes them for the dog:
        // rebuild each joint frame from the rig's own bone geometry (twist runs
        // DOWN the bone, swing is measured off it) and apply a limit table per
        // body part, plus a mass profile that puts most of the body in the
        // middle.
        // ------------------------------------------------------------------

        private static readonly HashSet<string> TorsoBones = new HashSet<string>
        {
            "CG", "Pelvis", "Spine", "Spine1", "Spine2",
        };

        private static bool IsTorsoBone(string boneName)
        {
            return TorsoBones.Contains(NormalizeBoneName(boneName));
        }

        private float MassMultiplierFor(string boneName)
        {
            string name = NormalizeBoneName(boneName);
            if (TorsoBones.Contains(name))
                return torsoMassMultiplier;
            // The head rides along; making it torso-heavy turns it into a
            // wrecking ball, making it limb-light gives a bobblehead
            if (name == "Head" || name == "Neck")
                return 1f;
            return limbMassMultiplier;
        }

        /// <summary>
        /// The bone each body "points at", used to find its long axis. Explicit
        /// rather than picking the furthest child: Spine2's children are the
        /// neck AND both clavicles, and the head's are hair/ears/eyebrows.
        /// A null entry means the bone is a leaf and is measured off its parent.
        /// </summary>
        private static readonly Dictionary<string, string> BoneTipNames = new Dictionary<string, string>
        {
            ["CG"] = "Spine1",
            ["Spine1"] = "Spine2",
            ["Spine2"] = "Neck",
            ["Head"] = null,
            ["L UpperArm"] = "L Forearm",
            ["R UpperArm"] = "R Forearm",
            ["L Forearm"] = "L Hand",
            ["R Forearm"] = "R Hand",
            ["L Hand"] = null,
            ["R Hand"] = null,
            ["L Thigh"] = "L Calf",
            ["R Thigh"] = "R Calf",
            ["L Calf"] = "L Foot",
            ["R Calf"] = "R Foot",
            ["L Foot"] = "L Toe0",
            ["R Foot"] = "R Toe0",
        };

        /// <summary>
        /// Limits per body part in the rebuilt frame, where twist is ROLL about
        /// the bone's own length and swing1/swing2 are the two bend planes.
        /// Elbows and knees are near-hinges that barely roll; shoulders and hips
        /// keep real range so the limbs still trail and swing; the spine is
        /// stiff so the torso drags as one mass. Swings are symmetric, so the
        /// hinges stay well under a full human flex rather than letting an elbow
        /// or knee bend the wrong way by the same amount.
        /// </summary>
        private static (float lowTwist, float highTwist, float swing1, float swing2) JointLimitsFor(string boneName)
        {
            string name = NormalizeBoneName(boneName);

            if (name.EndsWith("Forearm"))
                return (-5f, 5f, 40f, 5f);      // elbows
            if (name.EndsWith("Calf"))
                return (-5f, 5f, 35f, 5f);      // knees
            if (name.EndsWith("Hand"))
                return (-10f, 10f, 30f, 15f);   // wrists
            if (name.EndsWith("Foot"))
                return (-8f, 8f, 28f, 12f);     // ankles
            if (name.EndsWith("UpperArm"))
                return (-25f, 25f, 55f, 35f);   // shoulders
            if (name.EndsWith("Thigh"))
                return (-15f, 15f, 45f, 25f);   // hips
            if (name == "Head" || name == "Neck")
                return (-20f, 20f, 25f, 15f);
            return (-10f, 10f, 14f, 10f);       // spine
        }

        /// <summary>
        /// Rebuilds a joint's frame from the bone's own direction and applies
        /// the anatomical limits. Runs while the ragdoll is still inactive -
        /// joints bake their frames the moment they wake, so this has to happen
        /// before activation (see the spawn-holder comment in AttachToMouth).
        /// </summary>
        private static void TightenJoint(CharacterJoint joint, Transform ragdollRoot)
        {
            Vector3 twist = BoneLongAxis(joint.transform);
            joint.axis = twist;
            joint.swingAxis = SwingAxisFor(joint.transform, twist, ragdollRoot);

            var (lowTwist, highTwist, swing1, swing2) = JointLimitsFor(joint.name);
            joint.lowTwistLimit = new SoftJointLimit { limit = lowTwist };
            joint.highTwistLimit = new SoftJointLimit { limit = highTwist };
            joint.swing1Limit = new SoftJointLimit { limit = swing1 };
            joint.swing2Limit = new SoftJointLimit { limit = swing2 };
        }

        /// <summary>
        /// swing1 is measured about this axis, so on the elbows and knees it has
        /// to BE the flexion axis - point it anywhere else and the tight swing2
        /// ends up locking the plane the hinge is supposed to bend in. Read off
        /// the bend the limb is actually holding, and when the limb is near
        /// straight (no bend to measure) off the body's own left-right axis,
        /// which is the flexion axis for every hinge on a human.
        /// </summary>
        private static Vector3 SwingAxisFor(Transform bone, Vector3 twist, Transform ragdollRoot)
        {
            if (bone.parent != null)
            {
                Vector3 parentDirection = bone.InverseTransformDirection(
                    bone.parent.TransformDirection(BoneLongAxis(bone.parent)));
                Vector3 hinge = Vector3.Cross(parentDirection, twist);
                // Both are unit vectors, so this magnitude is sin(bend angle);
                // under ~10 degrees the limb is straight and the cross product
                // is just numerical noise
                if (hinge.magnitude > 0.17f)
                    return hinge.normalized;
            }

            if (ragdollRoot != null)
            {
                Vector3 lateral = Vector3.ProjectOnPlane(
                    bone.InverseTransformDirection(ragdollRoot.right), twist);
                if (lateral.sqrMagnitude > 1e-4f)
                    return lateral.normalized;
            }

            return Vector3.Cross(twist, Mathf.Abs(twist.y) < 0.9f ? Vector3.up : Vector3.right).normalized;
        }

        /// <summary>
        /// Unit vector down the bone's length, in the bone's own local space.
        /// </summary>
        private static Vector3 BoneLongAxis(Transform bone)
        {
            Vector3 world = Vector3.zero;

            if (BoneTipNames.TryGetValue(NormalizeBoneName(bone.name), out string tipName) && tipName != null)
            {
                Transform tip = FindDescendant(bone, tipName);
                if (tip != null)
                    world = tip.position - bone.position;
            }

            // A leaf (head, hands, a foot with no toe bone): the offset from its
            // parent is the closest thing to a length this bone has
            if (world.sqrMagnitude < 1e-8f && bone.parent != null)
                world = bone.position - bone.parent.position;

            if (world.sqrMagnitude < 1e-8f)
                return Vector3.up;

            Vector3 local = bone.InverseTransformDirection(world.normalized);
            return local.sqrMagnitude > 1e-8f ? local.normalized : Vector3.up;
        }

        private static Transform FindDescendant(Transform root, string normalizedName)
        {
            foreach (var child in root.GetComponentsInChildren<Transform>(true))
            {
                if (child != root && NormalizeBoneName(child.name) == normalizedName)
                    return child;
            }
            return null;
        }

        /// <summary>
        /// Post-activation physics setup - collision ignores and velocities
        /// need live physics actors.
        /// </summary>
        private void ReleaseBodies(Rigidbody[] bodies, Collider[] colliders, Rigidbody grabBody, Transform playerRoot)
        {
            // The body hangs beside the player's CharacterController capsule;
            // it must never collide with it or the limbs snag on the invisible
            // capsule (and the dog must not feel the body at all)
            Collider[] playerColliders = playerRoot != null
                ? playerRoot.GetComponentsInChildren<Collider>(true)
                : System.Array.Empty<Collider>();

            foreach (var ragdollCollider in colliders)
            {
                foreach (var playerCollider in playerColliders)
                    Physics.IgnoreCollision(ragdollCollider, playerCollider, true);
            }

            // Sideways kick out from under the dog, on top of (not clamped
            // with) the carried-over animation velocity - the sustained lean in
            // FixedUpdate is what holds it there, this just gets it clear now
            Vector3 sideKick = CarryLateralWorld() * (carrySide * carrySideImpulse);

            var boneLookup = BuildTrackedBoneLookup();
            foreach (var body in bodies)
            {
                if (body == grabBody)
                    continue;

                // Gradual handover: each limb keeps the velocity it had in the
                // fall animation instead of popping to a dead stop
                body.linearVelocity = EstimateBoneVelocity(body.name, boneLookup) + sideKick;
                // Most of the tumble goes to the limbs; a torso that spins on
                // its own axis undoes the weight the mass profile just gave it
                float tumble = IsTorsoBone(body.name) ? randomTumble * 0.25f : randomTumble;
                body.angularVelocity = Random.insideUnitSphere * tumble;
            }
        }

        // ------------------------------------------------------------------
        // Bone matching. The same skeleton reaches this code under three
        // spellings: the Malbers rig's own ("L Thigh"), the ragdoll's
        // "R_"-prefixed one ("R_L Thigh"), and the decoy model's, which came
        // back from Blender with the spaces turned into underscores
        // ("R_L_Thigh"). Normalizing to the bare, spaced name makes all three
        // match - and it is the rule the editor setup uses too, so the avatar,
        // the ragdoll and the limb lookups all agree.
        // ------------------------------------------------------------------

        public static string NormalizeBoneName(string name)
        {
            if (name.StartsWith("R_"))
                name = name.Substring(2);
            return name.Replace('_', ' ');
        }

        private Dictionary<string, int> BuildTrackedBoneLookup()
        {
            var lookup = new Dictionary<string, int>();
            for (int i = 0; i < trackedBones.Length; i++)
            {
                if (trackedBones[i] == null)
                    continue;
                string key = NormalizeBoneName(trackedBones[i].name);
                if (!lookup.ContainsKey(key))
                    lookup[key] = i;
            }
            return lookup;
        }

        private Vector3 EstimateBoneVelocity(string boneName, Dictionary<string, int> boneLookup)
        {
            if (!HasVelocityCapture || captureDeltaTime <= 0f)
                return Vector3.zero;
            if (!boneLookup.TryGetValue(NormalizeBoneName(boneName), out int index))
                return Vector3.zero;

            Vector3 velocity = (bonePositions[index] - prevBonePositions[index]) / captureDeltaTime;
            return Vector3.ClampMagnitude(velocity, boneVelocityClamp);
        }

        /// <summary>Poses the ragdoll skeleton to match the animated one.</summary>
        private static void CopyPose(Transform source, Transform target)
        {
            var sourceBones = new Dictionary<string, Transform>();
            foreach (var bone in source.GetComponentsInChildren<Transform>(true))
            {
                string key = NormalizeBoneName(bone.name);
                if (!sourceBones.ContainsKey(key))
                    sourceBones[key] = bone;
            }

            foreach (var bone in target.GetComponentsInChildren<Transform>(true))
            {
                if (bone == target)
                    continue;

                if (sourceBones.TryGetValue(NormalizeBoneName(bone.name), out var match))
                {
                    bone.localPosition = match.localPosition;
                    bone.localRotation = match.localRotation;
                }
            }
        }

        // Normalized bone names per limb, most-specific first. Every chain
        // additionally falls back to the spine (appended in ResolveLimbBody)
        // so a trimmed-down ragdoll variant still yields SOME pin.
        private static readonly Dictionary<DecoyLimb, string[]> LimbBoneChains = new Dictionary<DecoyLimb, string[]>
        {
            [DecoyLimb.RightForearm] = new[] { "R Forearm", "R Hand", "R UpperArm" },
            [DecoyLimb.LeftForearm] = new[] { "L Forearm", "L Hand", "L UpperArm" },
            [DecoyLimb.RightHand] = new[] { "R Hand", "R Forearm", "R UpperArm" },
            [DecoyLimb.LeftHand] = new[] { "L Hand", "L Forearm", "L UpperArm" },
            [DecoyLimb.RightUpperArm] = new[] { "R UpperArm", "R Forearm" },
            [DecoyLimb.LeftUpperArm] = new[] { "L UpperArm", "L Forearm" },
            [DecoyLimb.Head] = new[] { "Head", "Neck" },
            [DecoyLimb.Chest] = new[] { "Spine2", "Spine1", "CG" },
            [DecoyLimb.RightThigh] = new[] { "R Thigh", "R Calf" },
            [DecoyLimb.LeftThigh] = new[] { "L Thigh", "L Calf" },
            [DecoyLimb.RightCalf] = new[] { "R Calf", "R Thigh", "R Foot" },
            [DecoyLimb.LeftCalf] = new[] { "L Calf", "L Thigh", "L Foot" },
            [DecoyLimb.RightFoot] = new[] { "R Foot", "R Calf" },
            [DecoyLimb.LeftFoot] = new[] { "L Foot", "L Calf" },
        };

        /// <summary>The bone name a limb should ideally resolve to (no fallback).</summary>
        public static string PrimaryBoneName(DecoyLimb limb)
        {
            return LimbBoneChains.TryGetValue(limb, out var chain) ? chain[0] : "Spine2";
        }

        /// <summary>
        /// The rigidbody the mouth pin grabs for a limb, walking the limb's
        /// fallback chain and then the spine. Static so DecoySetup can validate
        /// full-limb coverage against the ragdoll prefab at build time.
        /// </summary>
        public static Rigidbody ResolveLimbBody(Transform ragdollRoot, DecoyLimb limb)
        {
            var bodies = ragdollRoot.GetComponentsInChildren<Rigidbody>(true);
            var chain = LimbBoneChains.TryGetValue(limb, out var names) ? names : System.Array.Empty<string>();

            foreach (string boneName in chain.Concat(new[] { "Spine2", "Spine1", "CG" }))
            {
                foreach (var body in bodies)
                {
                    if (NormalizeBoneName(body.name) == boneName)
                        return body;
                }
            }
            return null;
        }

        private void OnDestroy()
        {
            // The ragdoll and its anchor live under the dog's jaw once caught -
            // tear them down with the decoy so a chase cleanup can't orphan them
            if (mouthAnchor != null)
                Destroy(mouthAnchor.gameObject);
            else if (ragdollInstance != null)
                Destroy(ragdollInstance);
        }
    }
}
