using UnityEngine;

namespace RingSport.Player
{
    /// <summary>Trained positions used by the Simon Says mini-level.</summary>
    public enum DogPose
    {
        Stand = 0,
        Sit = 1,
        Down = 2
    }

    /// <summary>
    /// Thin wrapper around the dog model's Animator. PlayerController and the
    /// mini-levels drive it; it owns the parameter names, blend damping, and all
    /// code-driven model motion (clamber offset, dodge bank, jump pitch, camera
    /// facing). The Animator asset is generated by Tools > RingSport > Setup Dog Player.
    /// </summary>
    public class PlayerAnimator : MonoBehaviour
    {
        [SerializeField] private Animator animator;

        [Header("Blend Damping")]
        [SerializeField] private float moveSpeedDampTime = 0.2f;
        [SerializeField] private float strafeDampTime = 0.05f;

        [Header("Palisade Clamber")]
        [Tooltip("Local offset applied to the dog model while clambering, so the pull-up pose lines up with the palisade face.")]
        [SerializeField] private Vector3 clamberModelOffset = new Vector3(0f, 0f, -0.45f);
        [SerializeField] private float clamberOffsetBlendSpeed = 6f;
        [Tooltip("How fast the paused clamber clip scrubs toward the minigame progress, in normalized clip time per second.")]
        [SerializeField] private float clamberScrubSpeed = 1.5f;
        [Tooltip("Clip time the clamber scrubs to at full minigame progress; the vault plays the actual push over the top.")]
        [SerializeField] [Range(0f, 1f)] private float clamberMaxNormalizedTime = 0.75f;

        [Header("Mini-level Dodge")]
        [Tooltip("How far the model banks (rolls) into the dodge direction (degrees) - the pack has no true sideways-jump clip, so this sells the direction.")]
        [SerializeField] private float dodgeTiltAngle = 15f;
        [Tooltip("How far the body turns to face the hop direction (degrees) - Malbers rotates animals toward their motion direction (Turn Multiplier + smoothing); 90 = fully facing the hop direction.")]
        [SerializeField] private float dodgeTurnAngle = 50f;
        [Tooltip("How fast the body turns into (and back out of) the hop direction, degrees/sec.")]
        [SerializeField] private float dodgeTurnSpeed = 800f;
        [Tooltip("Point in the hop (state-normalized time, takeoff ~0.23 -> landing 1.0) where the body starts blending back to face forward, so the dog lands straight.")]
        [SerializeField] [Range(0f, 1f)] private float dodgeTurnReleaseStart = 0.6f;
        [Tooltip("Nose-up/nose-down through the hop arc. The dodge has no physics jump, so the velocity-based jump pitch never fires - this synthesizes it from the hop timeline.")]
        [SerializeField] private float dodgeHopPitchAngle = 8f;
        [SerializeField] private float dodgeTiltDuration = 0.4f;

        [Header("Lane-change Turn")]
        [Tooltip("How far the body turns toward the lateral motion on running lane changes and jumps (degrees) - same rotate-toward-motion logic as the mini-level dodge, scaled down because the motion is mostly forward.")]
        [SerializeField] private float laneTurnAngle = 30f;
        [Tooltip("How fast the body turns into and back out of the lane-change direction, degrees/sec.")]
        [SerializeField] private float laneTurnSpeed = 400f;

        [Header("Jump Pitch")]
        [Tooltip("Degrees of nose-up/nose-down per m/s of vertical velocity while airborne (Malbers-style pitch along the jump arc).")]
        [SerializeField] private float jumpPitchPerVelocity = 2f;
        [SerializeField] private float jumpMaxPitch = 25f;
        [SerializeField] private float jumpPitchChangeSpeed = 240f;

        [Header("Camera Facing")]
        [Tooltip("Turn speed (deg/sec) when the dog turns to face the camera for mini-levels and back again.")]
        [SerializeField] private float faceTurnSpeed = 270f;
        [Tooltip("Walk-blend amount fed into locomotion while the turn plays, so the feet move with the rotation.")]
        [SerializeField] private float faceTurnWalkAmount = 0.35f;

        [Header("Home Idle Flourishes")]
        [Tooltip("Random delay range (seconds) between idle flourishes (bark, shake, howl...) while the dog greets the player on the home screen.")]
        [SerializeField] private Vector2 flourishDelayRange = new Vector2(3f, 7f);
        [Tooltip("Blend time into a flourish state.")]
        [SerializeField] private float flourishBlendTime = 0.25f;

        private static readonly int MoveSpeedHash = Animator.StringToHash("MoveSpeed");
        private static readonly int StrafeHash = Animator.StringToHash("Strafe");
        private static readonly int AnimSpeedHash = Animator.StringToHash("AnimSpeed");
        private static readonly int GroundedHash = Animator.StringToHash("Grounded");
        private static readonly int JumpHash = Animator.StringToHash("Jump");
        private static readonly int VaultHash = Animator.StringToHash("Vault");
        private static readonly int ClamberHash = Animator.StringToHash("Clamber"); // bool param and state share the name
        private static readonly int DieHash = Animator.StringToHash("Die");
        private static readonly int PoseHash = Animator.StringToHash("Pose");
        private static readonly int DodgeLeftHash = Animator.StringToHash("DodgeLeft");
        private static readonly int DodgeRightHash = Animator.StringToHash("DodgeRight");
        private static readonly int LocomotionStateHash = Animator.StringToHash("Locomotion");
        private static readonly int DodgeLeftStateHash = Animator.StringToHash("Dodge Left");
        private static readonly int DodgeRightStateHash = Animator.StringToHash("Dodge Right");
        // Home-screen flourish states generated by DogPlayerSetup - names must match
        private static readonly int[] FlourishStateHashes =
        {
            Animator.StringToHash("Flourish Bark"),
            Animator.StringToHash("Flourish Shake"),
            Animator.StringToHash("Flourish Howl"),
            Animator.StringToHash("Flourish Glance"),
        };

        private Transform modelTransform;
        private Vector3 modelBasePosition;
        private Quaternion modelBaseRotation;
        private Vector3 modelBaseScale = Vector3.one;
        private float squashTimer = float.MaxValue;
        private float squashAmount;
        private float squashDuration = 0.16f;
        private bool isClambering;
        private float clamberOffsetWeight;
        private float clamberTargetProgress;
        private float clamberCurrentTime;
        private float dodgeTiltTimer = float.MaxValue;
        private float dodgeTiltSign;
        private float currentDodgeYaw;
        private float laneYawStrafe;
        private float currentLaneYaw;
        private float verticalVelocity;
        private bool isGroundedCached = true;
        private float currentJumpPitch;
        private float currentFacingYaw;
        private float targetFacingYaw;
        private Vector3 externalModelOffset;
        private bool flourishesEnabled;
        private float nextFlourishTime;

        /// <summary>True while the dog is (turned toward) the camera - mini-level mode.</summary>
        public bool FacingCamera => targetFacingYaw > 90f;

        private bool IsTurning => !Mathf.Approximately(currentFacingYaw, targetFacingYaw);

        private void Awake()
        {
            if (animator == null)
                animator = GetComponentInChildren<Animator>(true);

            if (animator == null)
            {
                Debug.LogWarning("PlayerAnimator: no Animator found in children. Run Tools > RingSport > Setup Dog Player.");
                return;
            }

            modelTransform = animator.transform;
            modelBasePosition = modelTransform.localPosition;
            modelBaseRotation = modelTransform.localRotation;
            modelBaseScale = modelTransform.localScale;

            // Time.timeScale is 0 during countdowns, mini-levels and game over,
            // so the animator must run on unscaled time or it freezes exactly
            // when the clamber and death animations need to play.
            animator.updateMode = AnimatorUpdateMode.UnscaledTime;
            animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
            animator.applyRootMotion = false;
        }

        private void Update()
        {
            if (animator == null)
                return;

            float deltaTime = Time.unscaledDeltaTime;

            // The Clamber state is paused (speed 0); scrub its playhead toward the
            // minigame progress so the dog only climbs while taps are landing.
            if (isClambering)
            {
                float targetTime = clamberTargetProgress * clamberMaxNormalizedTime;
                clamberCurrentTime = Mathf.MoveTowards(clamberCurrentTime, targetTime, clamberScrubSpeed * deltaTime);

                // Wait for the entry blend to finish (it shows the clip's first
                // frame) before forcing the playhead, or Play() would cut it short.
                if (!animator.IsInTransition(0) &&
                    animator.GetCurrentAnimatorStateInfo(0).shortNameHash == ClamberHash)
                {
                    animator.Play(ClamberHash, 0, clamberCurrentTime);
                }
            }

            clamberOffsetWeight = Mathf.MoveTowards(clamberOffsetWeight, isClambering ? 1f : 0f, clamberOffsetBlendSpeed * deltaTime);

            if (modelTransform == null)
                return;

            modelTransform.localPosition = modelBasePosition + clamberModelOffset * clamberOffsetWeight + externalModelOffset;

            // Camera facing: animated 180-degree turn for mini-levels and back
            currentFacingYaw = Mathf.MoveTowards(currentFacingYaw, targetFacingYaw, faceTurnSpeed * deltaTime);

            // Jump pitch: rotate into the arc - nose up while rising, nose down
            // while falling (what Malbers' controller does with root motion on)
            float targetPitch = isGroundedCached
                ? 0f
                : Mathf.Clamp(-verticalVelocity * jumpPitchPerVelocity, -jumpMaxPitch, jumpMaxPitch);
            currentJumpPitch = Mathf.MoveTowards(currentJumpPitch, targetPitch, jumpPitchChangeSpeed * deltaTime);

            // Dodge bank + hop pitch. The bank is front-loaded - strongest right
            // at takeoff, decaying through the hop; the pitch keeps the full arc
            // (nose up rising, nose down landing). Pitch is synthesized from the
            // hop timeline since the dodge has no physics jump for the
            // velocity-based pitch to react to.
            float dodgeRoll = 0f;
            float dodgePitch = 0f;
            if (dodgeTiltTimer < dodgeTiltDuration)
            {
                dodgeTiltTimer += deltaTime;
                float n = Mathf.Clamp01(dodgeTiltTimer / dodgeTiltDuration);
                float rollWeight = SmoothEdge(0f, 0.12f, n) * (1f - SmoothEdge(0.3f, 0.8f, n));
                float arcWeight = SmoothEdge(0f, 0.2f, n) * (1f - SmoothEdge(0.6f, 1f, n));
                dodgeRoll = dodgeTiltAngle * dodgeTiltSign * rollWeight;
                dodgePitch = -dodgeHopPitchAngle * (1f - 2f * n) * arcWeight;
            }

            // Dodge body-turn: rotate toward the hop direction, hold, then blend
            // back to face forward BEFORE touchdown (from dodgeTurnReleaseStart
            // of the Dodge state) so the dog lands straight
            var dodgeState = animator.GetCurrentAnimatorStateInfo(0);
            bool inDodge = dodgeState.shortNameHash == DodgeLeftStateHash ||
                           dodgeState.shortNameHash == DodgeRightStateHash;
            float hopT = 1f;
            if (inDodge)
            {
                hopT = dodgeState.normalizedTime;
            }
            else if (animator.IsInTransition(0))
            {
                var next = animator.GetNextAnimatorStateInfo(0);
                if (next.shortNameHash == DodgeLeftStateHash || next.shortNameHash == DodgeRightStateHash)
                {
                    inDodge = true;
                    hopT = next.normalizedTime;
                }
            }
            float turnRelease = 1f - SmoothEdge(dodgeTurnReleaseStart, 1f, Mathf.Clamp01(hopT));
            float dodgeYawTarget = inDodge ? dodgeTurnAngle * -dodgeTiltSign * turnRelease : 0f;
            currentDodgeYaw = Mathf.MoveTowards(currentDodgeYaw, dodgeYawTarget, dodgeTurnSpeed * deltaTime);

            // Running lane changes rotate the body toward the lateral motion the
            // same way (works airborne too - jumps share the lane lerp). The
            // lane lerp is exponential, so the raw strafe collapses within a few
            // frames - scaling the turn by it directly reads as no rotation.
            // Instead hold the FULL turn while the dog is still far from the
            // lane and release it over the final approach, like the dodge does
            float laneWeight = SmoothEdge(0.1f, 0.4f, Mathf.Abs(laneYawStrafe));
            float laneYawTarget = laneTurnAngle * Mathf.Sign(laneYawStrafe) * laneWeight;
            currentLaneYaw = Mathf.MoveTowards(currentLaneYaw, laneYawTarget, laneTurnSpeed * deltaTime);

            modelTransform.localRotation = modelBaseRotation *
                Quaternion.Euler(currentJumpPitch + dodgePitch, currentFacingYaw + currentDodgeYaw + currentLaneYaw, dodgeRoll);

            // Landing squash: deepest on impact, eased recovery, volume roughly
            // preserved by widening while flattening
            if (squashTimer < squashDuration)
            {
                squashTimer += deltaTime;
                if (squashTimer >= squashDuration)
                {
                    modelTransform.localScale = modelBaseScale;
                }
                else
                {
                    float w = 1f - Mathf.Clamp01(squashTimer / squashDuration);
                    w *= w;
                    modelTransform.localScale = new Vector3(
                        modelBaseScale.x * (1f + squashAmount * 0.6f * w),
                        modelBaseScale.y * (1f - squashAmount * w),
                        modelBaseScale.z * (1f + squashAmount * 0.6f * w));
                }
            }

            // Home screen: liven the idle with an occasional one-shot flourish
            if (flourishesEnabled && !IsTurning && Time.unscaledTime >= nextFlourishTime)
            {
                var current = animator.GetCurrentAnimatorStateInfo(0);
                if (current.shortNameHash == LocomotionStateHash && !animator.IsInTransition(0))
                {
                    int flourish = FlourishStateHashes[Random.Range(0, FlourishStateHashes.Length)];
                    // HasState guards against a stale controller missing the states
                    if (animator.HasState(0, flourish))
                        animator.CrossFadeInFixedTime(flourish, flourishBlendTime);
                }

                // Reschedule even when this attempt was skipped (mid-flourish,
                // mid-transition) so the check doesn't fire every frame
                ScheduleNextFlourish();
            }
        }

        /// <summary>
        /// While enabled (home screen), the idle is livened with random one-shot
        /// flourish states (bark, shake, howl...) on a flourishDelayRange timer.
        /// </summary>
        public void SetIdleFlourishes(bool enabled)
        {
            if (enabled && !flourishesEnabled)
                ScheduleNextFlourish();

            flourishesEnabled = enabled;
        }

        private void ScheduleNextFlourish()
        {
            nextFlourishTime = Time.unscaledTime + Random.Range(flourishDelayRange.x, flourishDelayRange.y);
        }

        /// <summary>
        /// moveSpeed: 0 = idle, 1 = run, 2 = sprint. strafe: -1..1 lane-change
        /// lean in WORLD space (flipped internally while facing the camera).
        /// animSpeed: playback multiplier on the locomotion cycle (level speed).
        /// </summary>
        public void UpdateLocomotion(float moveSpeed, float strafe, float animSpeed, float deltaTime)
        {
            if (animator == null)
                return;

            // Runner lane changes turn the body toward the lateral motion; the
            // mini-levels direct the model with the dodge states instead, and
            // the camera-facing turn feeds a synthetic strafe that must not leak
            laneYawStrafe = (!FacingCamera && !IsTurning) ? Mathf.Clamp(strafe, -1f, 1f) : 0f;

            // Facing the camera mirrors the model left/right on screen
            if (FacingCamera)
                strafe = -strafe;

            // While the facing turn plays, feed a walk-strafe so the feet move
            // with the rotation instead of pivoting on a frozen pose
            if (IsTurning)
            {
                moveSpeed = Mathf.Max(moveSpeed, faceTurnWalkAmount);
                strafe = targetFacingYaw > currentFacingYaw ? 1f : -1f;
            }

            animator.SetFloat(MoveSpeedHash, moveSpeed, moveSpeedDampTime, deltaTime);
            animator.SetFloat(StrafeHash, strafe, strafeDampTime, deltaTime);
            animator.SetFloat(AnimSpeedHash, animSpeed);
        }

        public void SetGrounded(bool grounded)
        {
            if (animator == null)
                return;

            isGroundedCached = grounded;
            animator.SetBool(GroundedHash, grounded);
        }

        /// <summary>Vertical velocity (m/s) from the movement code, for jump pitch.</summary>
        public void SetVerticalVelocity(float velocityY)
        {
            verticalVelocity = velocityY;
        }

        /// <summary>
        /// Extra offset on the dog model, purely visual (the CharacterController
        /// is untouched). The flee attack steers the pounce onto the decoy's
        /// grab limb with this. The player root doesn't rotate in the runner,
        /// so world space and local space agree. Cleared by ResetToLocomotion.
        /// </summary>
        public void SetModelOffset(Vector3 offset)
        {
            externalModelOffset = offset;
        }

        /// <summary>
        /// Freezes/unfreezes the whole animator mid-pose - the face attack
        /// holds the dog mid-pounce during its bullet-time limb pick.
        /// Movement pauses separately; this only stops the clips advancing.
        /// </summary>
        public void SetAnimatorPaused(bool paused)
        {
            if (animator != null)
                animator.speed = paused ? 0f : 1f;
        }

        /// <summary>
        /// Scales the whole animator's playback (slow-mo beats like the
        /// finish-line moment). 1 = normal. Reset by ResetToLocomotion.
        /// </summary>
        public void SetAnimatorTimeScale(float scale)
        {
            if (animator != null)
                animator.speed = Mathf.Max(0f, scale);
        }

        /// <summary>
        /// One-shot squash-and-stretch pulse on the model (landings): flattens
        /// by amount immediately, recovers over duration. Purely visual.
        /// </summary>
        public void PulseSquash(float amount = 0.12f, float duration = 0.16f)
        {
            squashAmount = amount;
            squashDuration = Mathf.Max(0.02f, duration);
            squashTimer = 0f;
        }

        /// <summary>
        /// Turn the dog around to face the camera (mini-levels) or back to the
        /// running direction. The turn is animated over faceTurnSpeed.
        /// towardYaw lets the home screen aim the dog at its angled start
        /// camera; the straight-on mini-level cameras use the default 180.
        /// </summary>
        public void SetFacing(bool towardCamera, float towardYaw = 180f)
        {
            targetFacingYaw = towardCamera ? towardYaw : 0f;
        }

        /// <summary>Snap the facing without the walk-turn (initial scene load).</summary>
        public void SetFacingImmediate(bool towardCamera, float towardYaw = 180f)
        {
            SetFacing(towardCamera, towardYaw);
            currentFacingYaw = targetFacingYaw;
        }

        public void TriggerJump()
        {
            if (animator == null)
                return;

            animator.SetTrigger(JumpHash);
        }

        /// <summary>Forward leap played after a successful palisade clamber.</summary>
        public void TriggerVault()
        {
            if (animator == null)
                return;

            animator.SetTrigger(VaultHash);
        }

        public void SetClambering(bool clambering)
        {
            if (animator == null)
                return;

            if (clambering && !isClambering)
            {
                clamberTargetProgress = 0f;
                clamberCurrentTime = 0f;
            }

            isClambering = clambering;
            animator.SetBool(ClamberHash, clambering);
        }

        /// <summary>
        /// Drives the clamber pull-up from the palisade minigame; pass the same
        /// 0..1 fill the progress bar shows so the climb tracks it.
        /// </summary>
        public void SetClamberProgress(float progress01)
        {
            clamberTargetProgress = Mathf.Clamp01(progress01);
        }

        /// <summary>Sideways slide-dodge for mini-level lane changes (Food Refusal). toRight is WORLD space.</summary>
        public void TriggerDodge(bool toRight)
        {
            if (animator == null)
                return;

            // Only dodge out of locomotion or another dodge - a trigger set while
            // posing (Simon Says) would linger and fire a spurious dodge later
            var state = animator.GetCurrentAnimatorStateInfo(0);
            if (!state.IsName("Locomotion") && !state.IsName("Dodge Left") && !state.IsName("Dodge Right"))
                return;

            // Facing the camera mirrors which side the dodge reads as
            bool modelRight = FacingCamera ? !toRight : toRight;

            animator.SetTrigger(modelRight ? DodgeRightHash : DodgeLeftHash);

            // Right dodge dips the right side: negative roll around +Z
            dodgeTiltSign = modelRight ? -1f : 1f;
            dodgeTiltTimer = 0f;
        }

        public void TriggerDeath()
        {
            if (animator == null)
                return;

            animator.SetTrigger(DieHash);
        }

        /// <summary>
        /// Sit/Down/Stand for the Simon Says mini-level. The controller routes
        /// through the authored transition clips (stand-to-sit, sit-to-lie, ...),
        /// chaining them when a pose is more than one step away.
        /// </summary>
        public void SetPose(DogPose pose)
        {
            if (animator == null)
                return;

            animator.SetInteger(PoseHash, (int)pose);
        }

        /// <summary>
        /// Shader-style smoothstep: 0 below edge0, 1 above edge1, smooth in
        /// between. NOT Mathf.SmoothStep - that one is a smoothed LERP from its
        /// first to its second argument, which silently scaled these envelopes
        /// to a ~0.4 ceiling when misused with edge semantics.
        /// </summary>
        private static float SmoothEdge(float edge0, float edge1, float x)
        {
            float t = Mathf.Clamp01((x - edge0) / (edge1 - edge0));
            return t * t * (3f - 2f * t);
        }

        /// <summary>Clears one-shot state (death, clamber) when a run restarts.</summary>
        public void ResetToLocomotion()
        {
            if (animator == null)
                return;

            animator.speed = 1f; // clear any face-attack mid-pounce freeze
            animator.ResetTrigger(JumpHash);
            animator.ResetTrigger(VaultHash);
            animator.ResetTrigger(DieHash);
            animator.ResetTrigger(DodgeLeftHash);
            animator.ResetTrigger(DodgeRightHash);
            animator.SetBool(ClamberHash, false);
            animator.SetInteger(PoseHash, 0);
            animator.SetFloat(MoveSpeedHash, 0f);
            animator.SetFloat(StrafeHash, 0f);
            isClambering = false;
            clamberTargetProgress = 0f;
            clamberCurrentTime = 0f;
            dodgeTiltTimer = float.MaxValue;
            currentDodgeYaw = 0f;
            laneYawStrafe = 0f;
            currentLaneYaw = 0f;
            currentJumpPitch = 0f;
            externalModelOffset = Vector3.zero;
            squashTimer = float.MaxValue;
            if (modelTransform != null)
                modelTransform.localScale = modelBaseScale;
            // Facing deliberately persists through resets - mini-level retries
            // keep the dog toward the camera; SetFacing owns turning back
            if (modelTransform != null)
                modelTransform.localRotation = modelBaseRotation * Quaternion.Euler(0f, currentFacingYaw, 0f);
            animator.Play(LocomotionStateHash, 0, 0f);
        }
    }
}
