using UnityEngine;

namespace RingSport.Player
{
    /// <summary>
    /// Thin wrapper around the dog model's Animator. PlayerController and the
    /// palisade minigame drive it; it owns the parameter names and blend damping.
    /// The Animator asset is generated by Tools > RingSport > Setup Dog Player.
    /// </summary>
    /// <summary>Trained positions used by the Simon Says mini-level.</summary>
    public enum DogPose
    {
        Stand = 0,
        Sit = 1,
        Down = 2
    }

    public class PlayerAnimator : MonoBehaviour
    {
        [SerializeField] private Animator animator;

        [Header("Blend Damping")]
        [SerializeField] private float moveSpeedDampTime = 0.2f;
        [SerializeField] private float strafeDampTime = 0.05f;

        [Header("Palisade Clamber")]
        [Tooltip("Local offset applied to the dog model while clambering, so the pull-up pose lines up with the palisade face.")]
        [SerializeField] private Vector3 clamberModelOffset = new Vector3(0f, 0f, -0.45f);
        [SerializeField] private float clamberOffsetBlendSpeed = 6f;
        [Tooltip("How fast the paused clamber clip scrubs toward the minigame progress, in normalized clip time per second.")]
        [SerializeField] private float clamberScrubSpeed = 1.5f;
        [Tooltip("Clip time the clamber scrubs to at full minigame progress; the vault plays the actual push over the top.")]
        [SerializeField] [Range(0f, 1f)] private float clamberMaxNormalizedTime = 0.75f;

        [Header("Mini-level Dodge")]
        [Tooltip("How far the model banks (rolls) into the dodge direction (degrees) - the pack has no true sideways-jump clip, so this sells the direction.")]
        [SerializeField] private float dodgeTiltAngle = 20f;
        [Tooltip("How far the nose turns toward the dodge direction (degrees).")]
        [SerializeField] private float dodgeYawAngle = 8f;
        [SerializeField] private float dodgeTiltDuration = 0.4f;

        private static readonly int MoveSpeedHash = Animator.StringToHash("MoveSpeed");
        private static readonly int StrafeHash = Animator.StringToHash("Strafe");
        private static readonly int AnimSpeedHash = Animator.StringToHash("AnimSpeed");
        private static readonly int GroundedHash = Animator.StringToHash("Grounded");
        private static readonly int JumpHash = Animator.StringToHash("Jump");
        private static readonly int VaultHash = Animator.StringToHash("Vault");
        private static readonly int ClamberHash = Animator.StringToHash("Clamber"); // bool param and state share the name
        private static readonly int DieHash = Animator.StringToHash("Die");
        private static readonly int PoseHash = Animator.StringToHash("Pose");
        private static readonly int DodgeLeftHash = Animator.StringToHash("DodgeLeft");
        private static readonly int DodgeRightHash = Animator.StringToHash("DodgeRight");
        private static readonly int LocomotionStateHash = Animator.StringToHash("Locomotion");

        private Transform modelTransform;
        private Vector3 modelBasePosition;
        private Quaternion modelBaseRotation;
        private bool isClambering;
        private float clamberOffsetWeight;
        private float clamberTargetProgress;
        private float clamberCurrentTime;
        private float dodgeTiltTimer = float.MaxValue;
        private float dodgeTiltSign;

        private void Awake()
        {
            if (animator == null)
                animator = GetComponentInChildren<Animator>(true);

            if (animator == null)
            {
                Debug.LogWarning("PlayerAnimator: no Animator found in children. Run Tools > RingSport > Setup Dog Player.");
                return;
            }

            modelTransform = animator.transform;
            modelBasePosition = modelTransform.localPosition;
            modelBaseRotation = modelTransform.localRotation;

            // Time.timeScale is 0 during countdowns, mini-levels and game over,
            // so the animator must run on unscaled time or it freezes exactly
            // when the clamber and death animations need to play.
            animator.updateMode = AnimatorUpdateMode.UnscaledTime;
            animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
            animator.applyRootMotion = false;
        }

        private void Update()
        {
            if (animator == null)
                return;

            float deltaTime = Time.unscaledDeltaTime;

            // The Clamber state is paused (speed 0); scrub its playhead toward the
            // minigame progress so the dog only climbs while taps are landing.
            if (isClambering)
            {
                float targetTime = clamberTargetProgress * clamberMaxNormalizedTime;
                clamberCurrentTime = Mathf.MoveTowards(clamberCurrentTime, targetTime, clamberScrubSpeed * deltaTime);

                // Wait for the entry blend to finish (it shows the clip's first
                // frame) before forcing the playhead, or Play() would cut it short.
                if (!animator.IsInTransition(0) &&
                    animator.GetCurrentAnimatorStateInfo(0).shortNameHash == ClamberHash)
                {
                    animator.Play(ClamberHash, 0, clamberCurrentTime);
                }
            }

            clamberOffsetWeight = Mathf.MoveTowards(clamberOffsetWeight, isClambering ? 1f : 0f, clamberOffsetBlendSpeed * deltaTime);
            if (modelTransform != null)
                modelTransform.localPosition = modelBasePosition + clamberModelOffset * clamberOffsetWeight;

            // Bank and turn into the dodge: fast ramp in, held through the hop,
            // eased out on landing - sustained rather than a brief mid-hop pulse
            if (modelTransform != null)
            {
                float roll = 0f;
                float yaw = 0f;
                if (dodgeTiltTimer < dodgeTiltDuration)
                {
                    dodgeTiltTimer += deltaTime;
                    float n = Mathf.Clamp01(dodgeTiltTimer / dodgeTiltDuration);
                    float weight = Mathf.SmoothStep(0f, 1f, n / 0.2f) * (1f - Mathf.SmoothStep(0.6f, 1f, n));
                    roll = dodgeTiltAngle * dodgeTiltSign * weight;
                    yaw = dodgeYawAngle * -dodgeTiltSign * weight;
                }
                modelTransform.localRotation = modelBaseRotation * Quaternion.Euler(0f, yaw, roll);
            }
        }

        /// <summary>
        /// moveSpeed: 0 = idle, 1 = run, 2 = sprint. strafe: -1..1 lane-change lean.
        /// animSpeed: playback multiplier on the locomotion cycle (level speed).
        /// </summary>
        public void UpdateLocomotion(float moveSpeed, float strafe, float animSpeed, float deltaTime)
        {
            if (animator == null)
                return;

            animator.SetFloat(MoveSpeedHash, moveSpeed, moveSpeedDampTime, deltaTime);
            animator.SetFloat(StrafeHash, strafe, strafeDampTime, deltaTime);
            animator.SetFloat(AnimSpeedHash, animSpeed);
        }

        public void SetGrounded(bool grounded)
        {
            if (animator == null)
                return;

            animator.SetBool(GroundedHash, grounded);
        }

        public void TriggerJump()
        {
            if (animator == null)
                return;

            animator.SetTrigger(JumpHash);
        }

        /// <summary>Forward leap played after a successful palisade clamber.</summary>
        public void TriggerVault()
        {
            if (animator == null)
                return;

            animator.SetTrigger(VaultHash);
        }

        public void SetClambering(bool clambering)
        {
            if (animator == null)
                return;

            if (clambering && !isClambering)
            {
                clamberTargetProgress = 0f;
                clamberCurrentTime = 0f;
            }

            isClambering = clambering;
            animator.SetBool(ClamberHash, clambering);
        }

        /// <summary>
        /// Drives the clamber pull-up from the palisade minigame; pass the same
        /// 0..1 fill the progress bar shows so the climb tracks it.
        /// </summary>
        public void SetClamberProgress(float progress01)
        {
            clamberTargetProgress = Mathf.Clamp01(progress01);
        }

        public void TriggerDeath()
        {
            if (animator == null)
                return;

            animator.SetTrigger(DieHash);
        }

        /// <summary>Sideways slide-dodge for mini-level lane changes (Food Refusal).</summary>
        public void TriggerDodge(bool toRight)
        {
            if (animator == null)
                return;

            // Only dodge out of locomotion or another dodge - a trigger set while
            // posing (Simon Says) would linger and fire a spurious dodge later
            var state = animator.GetCurrentAnimatorStateInfo(0);
            if (!state.IsName("Locomotion") && !state.IsName("Dodge Left") && !state.IsName("Dodge Right"))
                return;

            animator.SetTrigger(toRight ? DodgeRightHash : DodgeLeftHash);

            // Right dodge dips the right side: negative roll around +Z
            dodgeTiltSign = toRight ? -1f : 1f;
            dodgeTiltTimer = 0f;
        }

        /// <summary>
        /// Sit/Down/Stand for the Simon Says mini-level. The controller routes
        /// through the authored transition clips (stand-to-sit, sit-to-lie, ...),
        /// chaining them when a pose is more than one step away.
        /// </summary>
        public void SetPose(DogPose pose)
        {
            if (animator == null)
                return;

            animator.SetInteger(PoseHash, (int)pose);
        }

        /// <summary>Clears one-shot state (death, clamber) when a run restarts.</summary>
        public void ResetToLocomotion()
        {
            if (animator == null)
                return;

            animator.ResetTrigger(JumpHash);
            animator.ResetTrigger(VaultHash);
            animator.ResetTrigger(DieHash);
            animator.ResetTrigger(DodgeLeftHash);
            animator.ResetTrigger(DodgeRightHash);
            animator.SetBool(ClamberHash, false);
            animator.SetInteger(PoseHash, 0);
            animator.SetFloat(MoveSpeedHash, 0f);
            animator.SetFloat(StrafeHash, 0f);
            isClambering = false;
            clamberTargetProgress = 0f;
            clamberCurrentTime = 0f;
            dodgeTiltTimer = float.MaxValue;
            if (modelTransform != null)
                modelTransform.localRotation = modelBaseRotation;
            animator.Play(LocomotionStateHash, 0, 0f);
        }
    }
}
